// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,valid_types=protovalidate_required"
// @generated from file dtkt/flow/v1beta2/events.proto (package dtkt.flow.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Any } from "../../../google/protobuf/any_pb";
import { file_google_protobuf_any } from "../../../google/protobuf/any_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dtkt/flow/v1beta2/events.proto.
 */
export const file_dtkt_flow_v1beta2_events: GenFile = /*@__PURE__*/
  fileDesc("Ch5kdGt0L2Zsb3cvdjFiZXRhMi9ldmVudHMucHJvdG8SEWR0a3QuZmxvdy52MWJldGEyImgKCklucHV0RXZlbnQSLQoCaWQYASABKAlCIbpIHsgBAXIZMhdeW2EtekEtWl1bYS16QS1aMC05X10qJBIrCgV2YWx1ZRgCIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnlCBrpIA8gBASJCChFJbnB1dFJlcXVlc3RFdmVudBItCgJpZBgBIAEoCUIhukgeyAEBchkyF15bYS16QS1aXVthLXpBLVowLTlfXSokImkKC091dHB1dEV2ZW50Ei0KAmlkGAEgASgJQiG6SB7IAQFyGTIXXlthLXpBLVpdW2EtekEtWjAtOV9dKiQSKwoFdmFsdWUYAiABKAsyFC5nb29nbGUucHJvdG9idWYuQW55Qga6SAPIAQEiZAoXSW50ZXJhY3Rpb25SZXF1ZXN0RXZlbnQSLQoCaWQYASABKAlCIbpIHsgBAXIZMhdeW2EtekEtWl1bYS16QS1aMC05X10qJBIaCgV0b2tlbhgCIAEoCUILukgIyAEBcgOwAQEioQEKGEludGVyYWN0aW9uUmVzcG9uc2VFdmVudBItCgJpZBgBIAEoCUIhukgeyAEBchkyF15bYS16QS1aXVthLXpBLVowLTlfXSokEhoKBXRva2VuGAIgASgJQgu6SAjIAQFyA7ABARIrCgV2YWx1ZRgDIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnlCBrpIA8gBARINCgVhY3RvchgEIAEoCSIPCg1TdG9wRmxvd0V2ZW50IhQKElRlcm1pbmF0ZUZsb3dFdmVudCISChBTdXNwZW5kRmxvd0V2ZW50IhEKD1Jlc3VtZUZsb3dFdmVudCI+Cg1TdG9wTm9kZUV2ZW50Ei0KAmlkGAEgASgJQiG6SB7IAQFyGTIXXlthLXpBLVpdW2EtekEtWjAtOV9dKiQiQwoSVGVybWluYXRlTm9kZUV2ZW50Ei0KAmlkGAEgASgJQiG6SB7IAQFyGTIXXlthLXpBLVpdW2EtekEtWjAtOV9dKiQiQQoQU3VzcGVuZE5vZGVFdmVudBItCgJpZBgBIAEoCUIhukgeyAEBchkyF15bYS16QS1aXVthLXpBLVowLTlfXSokInQKD1Jlc3VtZU5vZGVFdmVudBItCgJpZBgBIAEoCUIhukgeyAEBchkyF15bYS16QS1aXVthLXpBLVowLTlfXSokEigKBXZhbHVlGAIgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueUgAiAEBQggKBl92YWx1ZSIQCg5TdGFydEZsb3dFdmVudELYAQoXcHJvdG8uZHRrdC5mbG93LnYxYmV0YTJCC0V2ZW50c1Byb3RvUAFaSmdpdGh1Yi5jb20vZGF0YWtpdC1kZXYvZHRrdC1zZGsvc2RrLWdvL3Byb3RvL2R0a3QvZmxvdy92MWJldGEyO2Zsb3d2MWJldGEyogIDREZYqgIRRHRrdC5GbG93LlYxYmV0YTLKAhFEdGt0XEZsb3dcVjFiZXRhMuICHUR0a3RcRmxvd1xWMWJldGEyXEdQQk1ldGFkYXRh6gITRHRrdDo6Rmxvdzo6VjFiZXRhMmIGcHJvdG8z", [file_buf_validate_validate, file_google_protobuf_any]);

/**
 * InputEvent is an externally-provided value for a specific input node.
 * Unsolicited push -- the external source sends data whenever it wants.
 *
 * @generated from message dtkt.flow.v1beta2.InputEvent
 */
export type InputEvent = Message<"dtkt.flow.v1beta2.InputEvent"> & {
  /**
   * Input node ID to deliver the value to.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The input value, serialized as a protobuf Any.
   *
   * @generated from field: google.protobuf.Any value = 2;
   */
  value?: Any;
};

/**
 * InputEvent is an externally-provided value for a specific input node.
 * Unsolicited push -- the external source sends data whenever it wants.
 *
 * @generated from message dtkt.flow.v1beta2.InputEvent
 */
export type InputEventValid = Message<"dtkt.flow.v1beta2.InputEvent"> & {
  /**
   * Input node ID to deliver the value to.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The input value, serialized as a protobuf Any.
   *
   * @generated from field: google.protobuf.Any value = 2;
   */
  value: Any;
};

/**
 * Describes the message dtkt.flow.v1beta2.InputEvent.
 * Use `create(InputEventSchema)` to create a new message.
 */
export const InputEventSchema: GenMessage<InputEvent, {validType: InputEventValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta2_events, 0);

/**
 * InputRequestEvent is emitted by the executor to solicit input for a
 * specific input node. The external source should respond with an InputEvent.
 *
 * @generated from message dtkt.flow.v1beta2.InputRequestEvent
 */
export type InputRequestEvent = Message<"dtkt.flow.v1beta2.InputRequestEvent"> & {
  /**
   * Input node ID that needs a value.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * InputRequestEvent is emitted by the executor to solicit input for a
 * specific input node. The external source should respond with an InputEvent.
 *
 * @generated from message dtkt.flow.v1beta2.InputRequestEvent
 */
export type InputRequestEventValid = Message<"dtkt.flow.v1beta2.InputRequestEvent"> & {
  /**
   * Input node ID that needs a value.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message dtkt.flow.v1beta2.InputRequestEvent.
 * Use `create(InputRequestEventSchema)` to create a new message.
 */
export const InputRequestEventSchema: GenMessage<InputRequestEvent, {validType: InputRequestEventValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta2_events, 1);

/**
 * OutputEvent is a result emitted by a specific output node.
 *
 * @generated from message dtkt.flow.v1beta2.OutputEvent
 */
export type OutputEvent = Message<"dtkt.flow.v1beta2.OutputEvent"> & {
  /**
   * Output node ID that produced the value.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The output value, serialized as a protobuf Any.
   *
   * @generated from field: google.protobuf.Any value = 2;
   */
  value?: Any;
};

/**
 * OutputEvent is a result emitted by a specific output node.
 *
 * @generated from message dtkt.flow.v1beta2.OutputEvent
 */
export type OutputEventValid = Message<"dtkt.flow.v1beta2.OutputEvent"> & {
  /**
   * Output node ID that produced the value.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The output value, serialized as a protobuf Any.
   *
   * @generated from field: google.protobuf.Any value = 2;
   */
  value: Any;
};

/**
 * Describes the message dtkt.flow.v1beta2.OutputEvent.
 * Use `create(OutputEventSchema)` to create a new message.
 */
export const OutputEventSchema: GenMessage<OutputEvent, {validType: OutputEventValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta2_events, 2);

/**
 * InteractionRequestEvent is emitted by the executor when an interaction node
 * needs external input. The token is a single-use opaque UUIDv7 that the
 * responder must echo back in InteractionResponseEvent.
 *
 * @generated from message dtkt.flow.v1beta2.InteractionRequestEvent
 */
export type InteractionRequestEvent = Message<"dtkt.flow.v1beta2.InteractionRequestEvent"> & {
  /**
   * Interaction node ID that needs a response.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Single-use opaque UUIDv7 token. Must be echoed in InteractionResponseEvent.
   *
   * @generated from field: string token = 2;
   */
  token: string;
};

/**
 * InteractionRequestEvent is emitted by the executor when an interaction node
 * needs external input. The token is a single-use opaque UUIDv7 that the
 * responder must echo back in InteractionResponseEvent.
 *
 * @generated from message dtkt.flow.v1beta2.InteractionRequestEvent
 */
export type InteractionRequestEventValid = Message<"dtkt.flow.v1beta2.InteractionRequestEvent"> & {
  /**
   * Interaction node ID that needs a response.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Single-use opaque UUIDv7 token. Must be echoed in InteractionResponseEvent.
   *
   * @generated from field: string token = 2;
   */
  token: string;
};

/**
 * Describes the message dtkt.flow.v1beta2.InteractionRequestEvent.
 * Use `create(InteractionRequestEventSchema)` to create a new message.
 */
export const InteractionRequestEventSchema: GenMessage<InteractionRequestEvent, {validType: InteractionRequestEventValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta2_events, 3);

/**
 * InteractionResponseEvent is sent by the external source in response to an
 * InteractionRequestEvent. The token must match the outstanding request;
 * mismatched or reused tokens are rejected.
 *
 * @generated from message dtkt.flow.v1beta2.InteractionResponseEvent
 */
export type InteractionResponseEvent = Message<"dtkt.flow.v1beta2.InteractionResponseEvent"> & {
  /**
   * Interaction node ID this response is for.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Token from the corresponding InteractionRequestEvent. Must match exactly.
   *
   * @generated from field: string token = 2;
   */
  token: string;

  /**
   * The response value, serialized as a protobuf Any.
   *
   * @generated from field: google.protobuf.Any value = 3;
   */
  value?: Any;

  /**
   * Actor is the resource name of the entity providing the response
   * (e.g. "users/bob", "agents/claude"). Stamped by the service layer
   * from auth context.
   *
   * @generated from field: string actor = 4;
   */
  actor: string;
};

/**
 * InteractionResponseEvent is sent by the external source in response to an
 * InteractionRequestEvent. The token must match the outstanding request;
 * mismatched or reused tokens are rejected.
 *
 * @generated from message dtkt.flow.v1beta2.InteractionResponseEvent
 */
export type InteractionResponseEventValid = Message<"dtkt.flow.v1beta2.InteractionResponseEvent"> & {
  /**
   * Interaction node ID this response is for.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Token from the corresponding InteractionRequestEvent. Must match exactly.
   *
   * @generated from field: string token = 2;
   */
  token: string;

  /**
   * The response value, serialized as a protobuf Any.
   *
   * @generated from field: google.protobuf.Any value = 3;
   */
  value: Any;

  /**
   * Actor is the resource name of the entity providing the response
   * (e.g. "users/bob", "agents/claude"). Stamped by the service layer
   * from auth context.
   *
   * @generated from field: string actor = 4;
   */
  actor: string;
};

/**
 * Describes the message dtkt.flow.v1beta2.InteractionResponseEvent.
 * Use `create(InteractionResponseEventSchema)` to create a new message.
 */
export const InteractionResponseEventSchema: GenMessage<InteractionResponseEvent, {validType: InteractionResponseEventValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta2_events, 4);

/**
 * StopFlowEvent requests a graceful shutdown of the entire flow.
 * Behavior: close all input EOFs, let in-flight messages drain through the
 * pipeline. Generators stop firing. Nodes complete their current work then
 * transition to PHASE_SUCCEEDED. Flow transitions RUNNING -> STOPPING ->
 * SUCCEEDED once all nodes have finished.
 *
 * @generated from message dtkt.flow.v1beta2.StopFlowEvent
 */
export type StopFlowEvent = Message<"dtkt.flow.v1beta2.StopFlowEvent"> & {
};

export type StopFlowEventValid = StopFlowEvent;

/**
 * Describes the message dtkt.flow.v1beta2.StopFlowEvent.
 * Use `create(StopFlowEventSchema)` to create a new message.
 */
export const StopFlowEventSchema: GenMessage<StopFlowEvent, {validType: StopFlowEventValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta2_events, 5);

/**
 * TerminateFlowEvent requests an immediate hard cancellation of the flow.
 * Behavior: cancel the flow context. Running nodes get their context cancelled
 * and transition to PHASE_CANCELLED (with an error if cancellation interrupted
 * an in-flight operation). No drain, no graceful flush. Flow transitions
 * RUNNING -> TERMINATING -> CANCELLED.
 *
 * @generated from message dtkt.flow.v1beta2.TerminateFlowEvent
 */
export type TerminateFlowEvent = Message<"dtkt.flow.v1beta2.TerminateFlowEvent"> & {
};

export type TerminateFlowEventValid = TerminateFlowEvent;

/**
 * Describes the message dtkt.flow.v1beta2.TerminateFlowEvent.
 * Use `create(TerminateFlowEventSchema)` to create a new message.
 */
export const TerminateFlowEventSchema: GenMessage<TerminateFlowEvent, {validType: TerminateFlowEventValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta2_events, 6);

/**
 * SuspendFlowEvent requests suspension of the entire flow.
 * Behavior: all nodes finish their current in-flight operation (like suspend-
 * after-current), then pause -- no new messages are processed, generators stop
 * publishing. Each node transitions to PHASE_SUSPENDED. Flow transitions
 * RUNNING -> SUSPENDED.
 *
 * Edge case: nodes already in a terminal phase (SUCCEEDED, FAILED, ERRORED,
 * CANCELLED) are left as-is -- only PENDING and RUNNING nodes are suspended.
 *
 * @generated from message dtkt.flow.v1beta2.SuspendFlowEvent
 */
export type SuspendFlowEvent = Message<"dtkt.flow.v1beta2.SuspendFlowEvent"> & {
};

export type SuspendFlowEventValid = SuspendFlowEvent;

/**
 * Describes the message dtkt.flow.v1beta2.SuspendFlowEvent.
 * Use `create(SuspendFlowEventSchema)` to create a new message.
 */
export const SuspendFlowEventSchema: GenMessage<SuspendFlowEvent, {validType: SuspendFlowEventValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta2_events, 7);

/**
 * ResumeFlowEvent requests resumption of a suspended, errored, or cancelled flow.
 * Behavior: all nodes in PHASE_SUSPENDED, PHASE_ERRORED, or PHASE_CANCELLED
 * transition back to PHASE_PENDING, then re-enter the normal execution loop.
 * Nodes already in terminal phases (SUCCEEDED, FAILED) are left as-is.
 * Flow transitions SUSPENDED/ERRORED -> RUNNING.
 *
 * If a resumed node hits the same error again, it will re-enter PHASE_ERRORED
 * and the flow's error_strategy applies as usual.
 *
 * Edge case: resuming a flow where some nodes succeeded and others errored --
 * the succeeded nodes stay done, errored nodes restart. Downstream nodes that
 * were starved (blocked waiting on the errored node) will begin receiving
 * messages again once the resumed node produces output.
 *
 * @generated from message dtkt.flow.v1beta2.ResumeFlowEvent
 */
export type ResumeFlowEvent = Message<"dtkt.flow.v1beta2.ResumeFlowEvent"> & {
};

export type ResumeFlowEventValid = ResumeFlowEvent;

/**
 * Describes the message dtkt.flow.v1beta2.ResumeFlowEvent.
 * Use `create(ResumeFlowEventSchema)` to create a new message.
 */
export const ResumeFlowEventSchema: GenMessage<ResumeFlowEvent, {validType: ResumeFlowEventValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta2_events, 8);

/**
 * StopNodeEvent requests a graceful shutdown of a specific node.
 * Behavior varies by node type:
 *   - Input: close the input (EOF), mark PHASE_SUCCEEDED when drained.
 *   - Generator: stop firing, mark PHASE_SUCCEEDED.
 *   - Var/Output: stop evaluating, mark PHASE_SUCCEEDED.
 *   - Action (unary): if idle, mark PHASE_SUCCEEDED immediately. If mid-RPC,
 *     wait for the current call to complete, then mark PHASE_SUCCEEDED.
 *   - Stream: close the request side (EOF), wait for server to close response
 *     side, then mark PHASE_SUCCEEDED.
 *   - Interaction: cancel outstanding token (if any), mark PHASE_SUCCEEDED.
 *
 * Stopping a node does NOT trigger the flow's error_strategy -- it is a clean
 * shutdown. Downstream dependents will be starved (no more messages).
 *
 * @generated from message dtkt.flow.v1beta2.StopNodeEvent
 */
export type StopNodeEvent = Message<"dtkt.flow.v1beta2.StopNodeEvent"> & {
  /**
   * Node ID to stop.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * StopNodeEvent requests a graceful shutdown of a specific node.
 * Behavior varies by node type:
 *   - Input: close the input (EOF), mark PHASE_SUCCEEDED when drained.
 *   - Generator: stop firing, mark PHASE_SUCCEEDED.
 *   - Var/Output: stop evaluating, mark PHASE_SUCCEEDED.
 *   - Action (unary): if idle, mark PHASE_SUCCEEDED immediately. If mid-RPC,
 *     wait for the current call to complete, then mark PHASE_SUCCEEDED.
 *   - Stream: close the request side (EOF), wait for server to close response
 *     side, then mark PHASE_SUCCEEDED.
 *   - Interaction: cancel outstanding token (if any), mark PHASE_SUCCEEDED.
 *
 * Stopping a node does NOT trigger the flow's error_strategy -- it is a clean
 * shutdown. Downstream dependents will be starved (no more messages).
 *
 * @generated from message dtkt.flow.v1beta2.StopNodeEvent
 */
export type StopNodeEventValid = Message<"dtkt.flow.v1beta2.StopNodeEvent"> & {
  /**
   * Node ID to stop.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message dtkt.flow.v1beta2.StopNodeEvent.
 * Use `create(StopNodeEventSchema)` to create a new message.
 */
export const StopNodeEventSchema: GenMessage<StopNodeEvent, {validType: StopNodeEventValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta2_events, 9);

/**
 * TerminateNodeEvent requests immediate cancellation of a specific node.
 * Behavior varies by node type:
 *   - Input/Generator/Var/Output: mark PHASE_CANCELLED immediately.
 *   - Action (unary): if idle, mark PHASE_CANCELLED. If mid-RPC, cancel the
 *     RPC context; node transitions to PHASE_CANCELLED with a CANCELLED error.
 *   - Stream: cancel the stream context, close both sides. Node transitions
 *     to PHASE_CANCELLED, with a CANCELLED error if the stream was active.
 *   - Interaction: cancel outstanding token, mark PHASE_CANCELLED.
 *
 * Terminating a node does NOT trigger the flow's error_strategy -- PHASE_CANCELLED
 * is distinct from PHASE_ERRORED. Downstream dependents will be starved.
 *
 * @generated from message dtkt.flow.v1beta2.TerminateNodeEvent
 */
export type TerminateNodeEvent = Message<"dtkt.flow.v1beta2.TerminateNodeEvent"> & {
  /**
   * Node ID to terminate.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * TerminateNodeEvent requests immediate cancellation of a specific node.
 * Behavior varies by node type:
 *   - Input/Generator/Var/Output: mark PHASE_CANCELLED immediately.
 *   - Action (unary): if idle, mark PHASE_CANCELLED. If mid-RPC, cancel the
 *     RPC context; node transitions to PHASE_CANCELLED with a CANCELLED error.
 *   - Stream: cancel the stream context, close both sides. Node transitions
 *     to PHASE_CANCELLED, with a CANCELLED error if the stream was active.
 *   - Interaction: cancel outstanding token, mark PHASE_CANCELLED.
 *
 * Terminating a node does NOT trigger the flow's error_strategy -- PHASE_CANCELLED
 * is distinct from PHASE_ERRORED. Downstream dependents will be starved.
 *
 * @generated from message dtkt.flow.v1beta2.TerminateNodeEvent
 */
export type TerminateNodeEventValid = Message<"dtkt.flow.v1beta2.TerminateNodeEvent"> & {
  /**
   * Node ID to terminate.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message dtkt.flow.v1beta2.TerminateNodeEvent.
 * Use `create(TerminateNodeEventSchema)` to create a new message.
 */
export const TerminateNodeEventSchema: GenMessage<TerminateNodeEvent, {validType: TerminateNodeEventValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta2_events, 10);

/**
 * SuspendNodeEvent requests suspension of a specific node.
 * Behavior: the node finishes its current in-flight operation, then pauses.
 * No new messages are processed; generators stop publishing.
 * Node transitions to PHASE_SUSPENDED.
 *
 * Streams: the stream stays open but no new request messages are sent and
 * incoming responses are buffered (not processed) until resumed.
 *
 * Edge case: if the node is already in a terminal phase (SUCCEEDED, FAILED,
 * ERRORED, CANCELLED), the command is a no-op.
 *
 * @generated from message dtkt.flow.v1beta2.SuspendNodeEvent
 */
export type SuspendNodeEvent = Message<"dtkt.flow.v1beta2.SuspendNodeEvent"> & {
  /**
   * Node ID to suspend.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * SuspendNodeEvent requests suspension of a specific node.
 * Behavior: the node finishes its current in-flight operation, then pauses.
 * No new messages are processed; generators stop publishing.
 * Node transitions to PHASE_SUSPENDED.
 *
 * Streams: the stream stays open but no new request messages are sent and
 * incoming responses are buffered (not processed) until resumed.
 *
 * Edge case: if the node is already in a terminal phase (SUCCEEDED, FAILED,
 * ERRORED, CANCELLED), the command is a no-op.
 *
 * @generated from message dtkt.flow.v1beta2.SuspendNodeEvent
 */
export type SuspendNodeEventValid = Message<"dtkt.flow.v1beta2.SuspendNodeEvent"> & {
  /**
   * Node ID to suspend.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message dtkt.flow.v1beta2.SuspendNodeEvent.
 * Use `create(SuspendNodeEventSchema)` to create a new message.
 */
export const SuspendNodeEventSchema: GenMessage<SuspendNodeEvent, {validType: SuspendNodeEventValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta2_events, 11);

/**
 * ResumeNodeEvent requests resumption of a specific suspended, errored, or
 * cancelled node. The node transitions back to PHASE_PENDING, then re-enters
 * the normal execution loop.
 *
 * If value is provided, it replaces the node's pending input for the next
 * evaluation. Use this to provide a corrected request when resuming an errored
 * action, or to inject a value into a suspended node. If absent, the node
 * restarts with its normal dependency resolution (re-evaluates from upstream).
 *
 * Edge case: resuming an errored action node -- the action will re-invoke the
 * RPC. If the same error occurs, it re-enters PHASE_ERRORED and error_strategy
 * applies again. The provided value (if any) is used as the MethodCall request.
 *
 * Edge case: resuming a node that is SUCCEEDED or FAILED is a no-op.
 *
 * @generated from message dtkt.flow.v1beta2.ResumeNodeEvent
 */
export type ResumeNodeEvent = Message<"dtkt.flow.v1beta2.ResumeNodeEvent"> & {
  /**
   * Node ID to resume.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Optional replacement value for the node's next evaluation.
   * If present, replaces the pending input (e.g. corrected RPC request).
   * If absent, the node re-evaluates from its upstream dependencies.
   *
   * @generated from field: optional google.protobuf.Any value = 2;
   */
  value?: Any;
};

/**
 * ResumeNodeEvent requests resumption of a specific suspended, errored, or
 * cancelled node. The node transitions back to PHASE_PENDING, then re-enters
 * the normal execution loop.
 *
 * If value is provided, it replaces the node's pending input for the next
 * evaluation. Use this to provide a corrected request when resuming an errored
 * action, or to inject a value into a suspended node. If absent, the node
 * restarts with its normal dependency resolution (re-evaluates from upstream).
 *
 * Edge case: resuming an errored action node -- the action will re-invoke the
 * RPC. If the same error occurs, it re-enters PHASE_ERRORED and error_strategy
 * applies again. The provided value (if any) is used as the MethodCall request.
 *
 * Edge case: resuming a node that is SUCCEEDED or FAILED is a no-op.
 *
 * @generated from message dtkt.flow.v1beta2.ResumeNodeEvent
 */
export type ResumeNodeEventValid = Message<"dtkt.flow.v1beta2.ResumeNodeEvent"> & {
  /**
   * Node ID to resume.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Optional replacement value for the node's next evaluation.
   * If present, replaces the pending input (e.g. corrected RPC request).
   * If absent, the node re-evaluates from its upstream dependencies.
   *
   * @generated from field: optional google.protobuf.Any value = 2;
   */
  value?: Any;
};

/**
 * Describes the message dtkt.flow.v1beta2.ResumeNodeEvent.
 * Use `create(ResumeNodeEventSchema)` to create a new message.
 */
export const ResumeNodeEventSchema: GenMessage<ResumeNodeEvent, {validType: ResumeNodeEventValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta2_events, 12);

/**
 * StartFlowEvent requests the executor to begin executing the flow graph.
 * Sent by the client after connecting to StreamFlowRunEvents to ensure the
 * event stream is established before any outputs are produced. The flow must
 * be in PENDING state; a start event on an already-running flow is a no-op.
 *
 * @generated from message dtkt.flow.v1beta2.StartFlowEvent
 */
export type StartFlowEvent = Message<"dtkt.flow.v1beta2.StartFlowEvent"> & {
};

export type StartFlowEventValid = StartFlowEvent;

/**
 * Describes the message dtkt.flow.v1beta2.StartFlowEvent.
 * Use `create(StartFlowEventSchema)` to create a new message.
 */
export const StartFlowEventSchema: GenMessage<StartFlowEvent, {validType: StartFlowEventValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta2_events, 13);

