legal:
- changed-files:
  - any-glob-to-any-file:
    - legal/**
    - LICENSE
    - NOTICE

secrets:
- changed-files:
  - any-glob-to-any-file: "**/secrets/**"

docs:
- changed-files:
  - any-glob-to-any-file: docs/**
- head-branch: docs/*

feature:
- head-branch: [feat/*, feature/*]

fix:
- head-branch: [fix/*, bugfix/*, hotfix/*]

chore:
- head-branch: chore/*

refactor:
- head-branch: refactor/*

perf:
- head-branch: perf/*

test:
- head-branch: test/*

build:
- head-branch: build/*

ci:
- head-branch: ci/*

style:
- head-branch: style/*
