// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: dtkt/base/v1beta1/services.proto

package basev1beta1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1beta1 "github.com/datakit-dev/dtkt-sdk/sdk-go/proto/dtkt/base/v1beta1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BaseServiceName is the fully-qualified name of the BaseService service.
	BaseServiceName = "dtkt.base.v1beta1.BaseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BaseServiceGetPackageProcedure is the fully-qualified name of the BaseService's GetPackage RPC.
	BaseServiceGetPackageProcedure = "/dtkt.base.v1beta1.BaseService/GetPackage"
	// BaseServiceCheckConfigProcedure is the fully-qualified name of the BaseService's CheckConfig RPC.
	BaseServiceCheckConfigProcedure = "/dtkt.base.v1beta1.BaseService/CheckConfig"
	// BaseServiceCheckAuthProcedure is the fully-qualified name of the BaseService's CheckAuth RPC.
	BaseServiceCheckAuthProcedure = "/dtkt.base.v1beta1.BaseService/CheckAuth"
	// BaseServiceListTypesProcedure is the fully-qualified name of the BaseService's ListTypes RPC.
	BaseServiceListTypesProcedure = "/dtkt.base.v1beta1.BaseService/ListTypes"
	// BaseServiceGetTypeProcedure is the fully-qualified name of the BaseService's GetType RPC.
	BaseServiceGetTypeProcedure = "/dtkt.base.v1beta1.BaseService/GetType"
)

// BaseServiceClient is a client for the dtkt.base.v1beta1.BaseService service.
type BaseServiceClient interface {
	// Returns the embedded package manifest (package.dtkt.yaml) and metadata.
	// NOTE: GetPackage is implemented by the Integration SDK (not by authors).
	GetPackage(context.Context, *connect.Request[v1beta1.GetPackageRequest]) (*connect.Response[v1beta1.GetPackageResponse], error)
	// Validates config, allocates instances, and .
	// NOTE: CheckConfig is implemented by the Integration SDK (not by authors).
	CheckConfig(context.Context, *connect.Request[v1beta1.CheckConfigRequest]) (*connect.Response[v1beta1.CheckConfigResponse], error)
	// Orchestrates OAuth checks/exchanges (3-legged).
	CheckAuth(context.Context, *connect.Request[v1beta1.CheckAuthRequest]) (*connect.Response[v1beta1.CheckAuthResponse], error)
	// Returns types registered to integration (through use of integration's type
	// registry) typically from registered actions, events, and event sources.
	// NOTE: ListTypes is implemented by the Integration SDK (not by authors).
	ListTypes(context.Context, *connect.Request[v1beta1.ListTypesRequest]) (*connect.Response[v1beta1.ListTypesResponse], error)
	// Returns type registered to integration.
	// NOTE: GetType is implemented by the Integration SDK (not by authors).
	GetType(context.Context, *connect.Request[v1beta1.GetTypeRequest]) (*connect.Response[v1beta1.GetTypeResponse], error)
}

// NewBaseServiceClient constructs a client for the dtkt.base.v1beta1.BaseService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBaseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BaseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	baseServiceMethods := v1beta1.File_dtkt_base_v1beta1_services_proto.Services().ByName("BaseService").Methods()
	return &baseServiceClient{
		getPackage: connect.NewClient[v1beta1.GetPackageRequest, v1beta1.GetPackageResponse](
			httpClient,
			baseURL+BaseServiceGetPackageProcedure,
			connect.WithSchema(baseServiceMethods.ByName("GetPackage")),
			connect.WithClientOptions(opts...),
		),
		checkConfig: connect.NewClient[v1beta1.CheckConfigRequest, v1beta1.CheckConfigResponse](
			httpClient,
			baseURL+BaseServiceCheckConfigProcedure,
			connect.WithSchema(baseServiceMethods.ByName("CheckConfig")),
			connect.WithClientOptions(opts...),
		),
		checkAuth: connect.NewClient[v1beta1.CheckAuthRequest, v1beta1.CheckAuthResponse](
			httpClient,
			baseURL+BaseServiceCheckAuthProcedure,
			connect.WithSchema(baseServiceMethods.ByName("CheckAuth")),
			connect.WithClientOptions(opts...),
		),
		listTypes: connect.NewClient[v1beta1.ListTypesRequest, v1beta1.ListTypesResponse](
			httpClient,
			baseURL+BaseServiceListTypesProcedure,
			connect.WithSchema(baseServiceMethods.ByName("ListTypes")),
			connect.WithClientOptions(opts...),
		),
		getType: connect.NewClient[v1beta1.GetTypeRequest, v1beta1.GetTypeResponse](
			httpClient,
			baseURL+BaseServiceGetTypeProcedure,
			connect.WithSchema(baseServiceMethods.ByName("GetType")),
			connect.WithClientOptions(opts...),
		),
	}
}

// baseServiceClient implements BaseServiceClient.
type baseServiceClient struct {
	getPackage  *connect.Client[v1beta1.GetPackageRequest, v1beta1.GetPackageResponse]
	checkConfig *connect.Client[v1beta1.CheckConfigRequest, v1beta1.CheckConfigResponse]
	checkAuth   *connect.Client[v1beta1.CheckAuthRequest, v1beta1.CheckAuthResponse]
	listTypes   *connect.Client[v1beta1.ListTypesRequest, v1beta1.ListTypesResponse]
	getType     *connect.Client[v1beta1.GetTypeRequest, v1beta1.GetTypeResponse]
}

// GetPackage calls dtkt.base.v1beta1.BaseService.GetPackage.
func (c *baseServiceClient) GetPackage(ctx context.Context, req *connect.Request[v1beta1.GetPackageRequest]) (*connect.Response[v1beta1.GetPackageResponse], error) {
	return c.getPackage.CallUnary(ctx, req)
}

// CheckConfig calls dtkt.base.v1beta1.BaseService.CheckConfig.
func (c *baseServiceClient) CheckConfig(ctx context.Context, req *connect.Request[v1beta1.CheckConfigRequest]) (*connect.Response[v1beta1.CheckConfigResponse], error) {
	return c.checkConfig.CallUnary(ctx, req)
}

// CheckAuth calls dtkt.base.v1beta1.BaseService.CheckAuth.
func (c *baseServiceClient) CheckAuth(ctx context.Context, req *connect.Request[v1beta1.CheckAuthRequest]) (*connect.Response[v1beta1.CheckAuthResponse], error) {
	return c.checkAuth.CallUnary(ctx, req)
}

// ListTypes calls dtkt.base.v1beta1.BaseService.ListTypes.
func (c *baseServiceClient) ListTypes(ctx context.Context, req *connect.Request[v1beta1.ListTypesRequest]) (*connect.Response[v1beta1.ListTypesResponse], error) {
	return c.listTypes.CallUnary(ctx, req)
}

// GetType calls dtkt.base.v1beta1.BaseService.GetType.
func (c *baseServiceClient) GetType(ctx context.Context, req *connect.Request[v1beta1.GetTypeRequest]) (*connect.Response[v1beta1.GetTypeResponse], error) {
	return c.getType.CallUnary(ctx, req)
}

// BaseServiceHandler is an implementation of the dtkt.base.v1beta1.BaseService service.
type BaseServiceHandler interface {
	// Returns the embedded package manifest (package.dtkt.yaml) and metadata.
	// NOTE: GetPackage is implemented by the Integration SDK (not by authors).
	GetPackage(context.Context, *connect.Request[v1beta1.GetPackageRequest]) (*connect.Response[v1beta1.GetPackageResponse], error)
	// Validates config, allocates instances, and .
	// NOTE: CheckConfig is implemented by the Integration SDK (not by authors).
	CheckConfig(context.Context, *connect.Request[v1beta1.CheckConfigRequest]) (*connect.Response[v1beta1.CheckConfigResponse], error)
	// Orchestrates OAuth checks/exchanges (3-legged).
	CheckAuth(context.Context, *connect.Request[v1beta1.CheckAuthRequest]) (*connect.Response[v1beta1.CheckAuthResponse], error)
	// Returns types registered to integration (through use of integration's type
	// registry) typically from registered actions, events, and event sources.
	// NOTE: ListTypes is implemented by the Integration SDK (not by authors).
	ListTypes(context.Context, *connect.Request[v1beta1.ListTypesRequest]) (*connect.Response[v1beta1.ListTypesResponse], error)
	// Returns type registered to integration.
	// NOTE: GetType is implemented by the Integration SDK (not by authors).
	GetType(context.Context, *connect.Request[v1beta1.GetTypeRequest]) (*connect.Response[v1beta1.GetTypeResponse], error)
}

// NewBaseServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBaseServiceHandler(svc BaseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	baseServiceMethods := v1beta1.File_dtkt_base_v1beta1_services_proto.Services().ByName("BaseService").Methods()
	baseServiceGetPackageHandler := connect.NewUnaryHandler(
		BaseServiceGetPackageProcedure,
		svc.GetPackage,
		connect.WithSchema(baseServiceMethods.ByName("GetPackage")),
		connect.WithHandlerOptions(opts...),
	)
	baseServiceCheckConfigHandler := connect.NewUnaryHandler(
		BaseServiceCheckConfigProcedure,
		svc.CheckConfig,
		connect.WithSchema(baseServiceMethods.ByName("CheckConfig")),
		connect.WithHandlerOptions(opts...),
	)
	baseServiceCheckAuthHandler := connect.NewUnaryHandler(
		BaseServiceCheckAuthProcedure,
		svc.CheckAuth,
		connect.WithSchema(baseServiceMethods.ByName("CheckAuth")),
		connect.WithHandlerOptions(opts...),
	)
	baseServiceListTypesHandler := connect.NewUnaryHandler(
		BaseServiceListTypesProcedure,
		svc.ListTypes,
		connect.WithSchema(baseServiceMethods.ByName("ListTypes")),
		connect.WithHandlerOptions(opts...),
	)
	baseServiceGetTypeHandler := connect.NewUnaryHandler(
		BaseServiceGetTypeProcedure,
		svc.GetType,
		connect.WithSchema(baseServiceMethods.ByName("GetType")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dtkt.base.v1beta1.BaseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BaseServiceGetPackageProcedure:
			baseServiceGetPackageHandler.ServeHTTP(w, r)
		case BaseServiceCheckConfigProcedure:
			baseServiceCheckConfigHandler.ServeHTTP(w, r)
		case BaseServiceCheckAuthProcedure:
			baseServiceCheckAuthHandler.ServeHTTP(w, r)
		case BaseServiceListTypesProcedure:
			baseServiceListTypesHandler.ServeHTTP(w, r)
		case BaseServiceGetTypeProcedure:
			baseServiceGetTypeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBaseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBaseServiceHandler struct{}

func (UnimplementedBaseServiceHandler) GetPackage(context.Context, *connect.Request[v1beta1.GetPackageRequest]) (*connect.Response[v1beta1.GetPackageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.base.v1beta1.BaseService.GetPackage is not implemented"))
}

func (UnimplementedBaseServiceHandler) CheckConfig(context.Context, *connect.Request[v1beta1.CheckConfigRequest]) (*connect.Response[v1beta1.CheckConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.base.v1beta1.BaseService.CheckConfig is not implemented"))
}

func (UnimplementedBaseServiceHandler) CheckAuth(context.Context, *connect.Request[v1beta1.CheckAuthRequest]) (*connect.Response[v1beta1.CheckAuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.base.v1beta1.BaseService.CheckAuth is not implemented"))
}

func (UnimplementedBaseServiceHandler) ListTypes(context.Context, *connect.Request[v1beta1.ListTypesRequest]) (*connect.Response[v1beta1.ListTypesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.base.v1beta1.BaseService.ListTypes is not implemented"))
}

func (UnimplementedBaseServiceHandler) GetType(context.Context, *connect.Request[v1beta1.GetTypeRequest]) (*connect.Response[v1beta1.GetTypeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.base.v1beta1.BaseService.GetType is not implemented"))
}
