// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: dtkt/replication/v1beta1/enums.proto

package replicationv1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncStatus int32

const (
	// Unspecified sync status.
	SyncStatus_SYNC_STATUS_UNSPECIFIED SyncStatus = 0
	// Scheduled sync status.
	SyncStatus_SYNC_STATUS_SCHEDULED SyncStatus = 1
	// Running sync status.
	SyncStatus_SYNC_STATUS_RUNNING SyncStatus = 2
	// Success sync status.
	SyncStatus_SYNC_STATUS_SUCCESS SyncStatus = 3
	// Failed sync status.
	SyncStatus_SYNC_STATUS_FAILED SyncStatus = 4
)

// Enum value maps for SyncStatus.
var (
	SyncStatus_name = map[int32]string{
		0: "SYNC_STATUS_UNSPECIFIED",
		1: "SYNC_STATUS_SCHEDULED",
		2: "SYNC_STATUS_RUNNING",
		3: "SYNC_STATUS_SUCCESS",
		4: "SYNC_STATUS_FAILED",
	}
	SyncStatus_value = map[string]int32{
		"SYNC_STATUS_UNSPECIFIED": 0,
		"SYNC_STATUS_SCHEDULED":   1,
		"SYNC_STATUS_RUNNING":     2,
		"SYNC_STATUS_SUCCESS":     3,
		"SYNC_STATUS_FAILED":      4,
	}
)

func (x SyncStatus) Enum() *SyncStatus {
	p := new(SyncStatus)
	*p = x
	return p
}

func (x SyncStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_dtkt_replication_v1beta1_enums_proto_enumTypes[0].Descriptor()
}

func (SyncStatus) Type() protoreflect.EnumType {
	return &file_dtkt_replication_v1beta1_enums_proto_enumTypes[0]
}

func (x SyncStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncStatus.Descriptor instead.
func (SyncStatus) EnumDescriptor() ([]byte, []int) {
	return file_dtkt_replication_v1beta1_enums_proto_rawDescGZIP(), []int{0}
}

var File_dtkt_replication_v1beta1_enums_proto protoreflect.FileDescriptor

const file_dtkt_replication_v1beta1_enums_proto_rawDesc = "" +
	"\n" +
	"$dtkt/replication/v1beta1/enums.proto\x12\x18dtkt.replication.v1beta1*\x8e\x01\n" +
	"\n" +
	"SyncStatus\x12\x1b\n" +
	"\x17SYNC_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SYNC_STATUS_SCHEDULED\x10\x01\x12\x17\n" +
	"\x13SYNC_STATUS_RUNNING\x10\x02\x12\x17\n" +
	"\x13SYNC_STATUS_SUCCESS\x10\x03\x12\x16\n" +
	"\x12SYNC_STATUS_FAILED\x10\x04B\x88\x02\n" +
	"\x1eproto.dtkt.replication.v1beta1B\n" +
	"EnumsProtoP\x01ZXgithub.com/datakit-dev/dtkt-sdk/sdk-go/proto/dtkt/replication/v1beta1;replicationv1beta1\xa2\x02\x03DRX\xaa\x02\x18Dtkt.Replication.V1beta1\xca\x02\x18Dtkt\\Replication\\V1beta1\xe2\x02$Dtkt\\Replication\\V1beta1\\GPBMetadata\xea\x02\x1aDtkt::Replication::V1beta1b\x06proto3"

var (
	file_dtkt_replication_v1beta1_enums_proto_rawDescOnce sync.Once
	file_dtkt_replication_v1beta1_enums_proto_rawDescData []byte
)

func file_dtkt_replication_v1beta1_enums_proto_rawDescGZIP() []byte {
	file_dtkt_replication_v1beta1_enums_proto_rawDescOnce.Do(func() {
		file_dtkt_replication_v1beta1_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dtkt_replication_v1beta1_enums_proto_rawDesc), len(file_dtkt_replication_v1beta1_enums_proto_rawDesc)))
	})
	return file_dtkt_replication_v1beta1_enums_proto_rawDescData
}

var file_dtkt_replication_v1beta1_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dtkt_replication_v1beta1_enums_proto_goTypes = []any{
	(SyncStatus)(0), // 0: dtkt.replication.v1beta1.SyncStatus
}
var file_dtkt_replication_v1beta1_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dtkt_replication_v1beta1_enums_proto_init() }
func file_dtkt_replication_v1beta1_enums_proto_init() {
	if File_dtkt_replication_v1beta1_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dtkt_replication_v1beta1_enums_proto_rawDesc), len(file_dtkt_replication_v1beta1_enums_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dtkt_replication_v1beta1_enums_proto_goTypes,
		DependencyIndexes: file_dtkt_replication_v1beta1_enums_proto_depIdxs,
		EnumInfos:         file_dtkt_replication_v1beta1_enums_proto_enumTypes,
	}.Build()
	File_dtkt_replication_v1beta1_enums_proto = out.File
	file_dtkt_replication_v1beta1_enums_proto_goTypes = nil
	file_dtkt_replication_v1beta1_enums_proto_depIdxs = nil
}
