// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: dtkt/ai/v1beta1/services.proto

package aiv1beta1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1beta1 "github.com/datakit-dev/dtkt-sdk/sdk-go/proto/dtkt/ai/v1beta1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TextServiceName is the fully-qualified name of the TextService service.
	TextServiceName = "dtkt.ai.v1beta1.TextService"
	// ObjectServiceName is the fully-qualified name of the ObjectService service.
	ObjectServiceName = "dtkt.ai.v1beta1.ObjectService"
	// EmbeddingServiceName is the fully-qualified name of the EmbeddingService service.
	EmbeddingServiceName = "dtkt.ai.v1beta1.EmbeddingService"
	// ImageServiceName is the fully-qualified name of the ImageService service.
	ImageServiceName = "dtkt.ai.v1beta1.ImageService"
	// TranscriptionServiceName is the fully-qualified name of the TranscriptionService service.
	TranscriptionServiceName = "dtkt.ai.v1beta1.TranscriptionService"
	// SpeechServiceName is the fully-qualified name of the SpeechService service.
	SpeechServiceName = "dtkt.ai.v1beta1.SpeechService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TextServiceGenerateTextProcedure is the fully-qualified name of the TextService's GenerateText
	// RPC.
	TextServiceGenerateTextProcedure = "/dtkt.ai.v1beta1.TextService/GenerateText"
	// TextServiceStreamTextProcedure is the fully-qualified name of the TextService's StreamText RPC.
	TextServiceStreamTextProcedure = "/dtkt.ai.v1beta1.TextService/StreamText"
	// ObjectServiceGenerateObjectProcedure is the fully-qualified name of the ObjectService's
	// GenerateObject RPC.
	ObjectServiceGenerateObjectProcedure = "/dtkt.ai.v1beta1.ObjectService/GenerateObject"
	// ObjectServiceStreamObjectsProcedure is the fully-qualified name of the ObjectService's
	// StreamObjects RPC.
	ObjectServiceStreamObjectsProcedure = "/dtkt.ai.v1beta1.ObjectService/StreamObjects"
	// EmbeddingServiceListEmbeddingModelsProcedure is the fully-qualified name of the
	// EmbeddingService's ListEmbeddingModels RPC.
	EmbeddingServiceListEmbeddingModelsProcedure = "/dtkt.ai.v1beta1.EmbeddingService/ListEmbeddingModels"
	// EmbeddingServiceGetEmbeddingModelProcedure is the fully-qualified name of the EmbeddingService's
	// GetEmbeddingModel RPC.
	EmbeddingServiceGetEmbeddingModelProcedure = "/dtkt.ai.v1beta1.EmbeddingService/GetEmbeddingModel"
	// EmbeddingServiceGenerateEmbeddingsProcedure is the fully-qualified name of the EmbeddingService's
	// GenerateEmbeddings RPC.
	EmbeddingServiceGenerateEmbeddingsProcedure = "/dtkt.ai.v1beta1.EmbeddingService/GenerateEmbeddings"
	// ImageServiceGenerateImageProcedure is the fully-qualified name of the ImageService's
	// GenerateImage RPC.
	ImageServiceGenerateImageProcedure = "/dtkt.ai.v1beta1.ImageService/GenerateImage"
	// ImageServiceGenerateImagesProcedure is the fully-qualified name of the ImageService's
	// GenerateImages RPC.
	ImageServiceGenerateImagesProcedure = "/dtkt.ai.v1beta1.ImageService/GenerateImages"
	// ImageServiceGenerateBatchImagesProcedure is the fully-qualified name of the ImageService's
	// GenerateBatchImages RPC.
	ImageServiceGenerateBatchImagesProcedure = "/dtkt.ai.v1beta1.ImageService/GenerateBatchImages"
	// TranscriptionServiceTranscribeProcedure is the fully-qualified name of the TranscriptionService's
	// Transcribe RPC.
	TranscriptionServiceTranscribeProcedure = "/dtkt.ai.v1beta1.TranscriptionService/Transcribe"
	// SpeechServiceGenerateSpeechProcedure is the fully-qualified name of the SpeechService's
	// GenerateSpeech RPC.
	SpeechServiceGenerateSpeechProcedure = "/dtkt.ai.v1beta1.SpeechService/GenerateSpeech"
	// SpeechServiceStreamSpeechProcedure is the fully-qualified name of the SpeechService's
	// StreamSpeech RPC.
	SpeechServiceStreamSpeechProcedure = "/dtkt.ai.v1beta1.SpeechService/StreamSpeech"
)

// TextServiceClient is a client for the dtkt.ai.v1beta1.TextService service.
type TextServiceClient interface {
	// Generates text for the provided input using a specified model.
	GenerateText(context.Context, *connect.Request[v1beta1.GenerateTextRequest]) (*connect.Response[v1beta1.GenerateTextResponse], error)
	// Streams text for the provided input using a specified model.
	StreamText(context.Context, *connect.Request[v1beta1.StreamTextRequest]) (*connect.ServerStreamForClient[v1beta1.StreamTextResponse], error)
}

// NewTextServiceClient constructs a client for the dtkt.ai.v1beta1.TextService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTextServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TextServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	textServiceMethods := v1beta1.File_dtkt_ai_v1beta1_services_proto.Services().ByName("TextService").Methods()
	return &textServiceClient{
		generateText: connect.NewClient[v1beta1.GenerateTextRequest, v1beta1.GenerateTextResponse](
			httpClient,
			baseURL+TextServiceGenerateTextProcedure,
			connect.WithSchema(textServiceMethods.ByName("GenerateText")),
			connect.WithClientOptions(opts...),
		),
		streamText: connect.NewClient[v1beta1.StreamTextRequest, v1beta1.StreamTextResponse](
			httpClient,
			baseURL+TextServiceStreamTextProcedure,
			connect.WithSchema(textServiceMethods.ByName("StreamText")),
			connect.WithClientOptions(opts...),
		),
	}
}

// textServiceClient implements TextServiceClient.
type textServiceClient struct {
	generateText *connect.Client[v1beta1.GenerateTextRequest, v1beta1.GenerateTextResponse]
	streamText   *connect.Client[v1beta1.StreamTextRequest, v1beta1.StreamTextResponse]
}

// GenerateText calls dtkt.ai.v1beta1.TextService.GenerateText.
func (c *textServiceClient) GenerateText(ctx context.Context, req *connect.Request[v1beta1.GenerateTextRequest]) (*connect.Response[v1beta1.GenerateTextResponse], error) {
	return c.generateText.CallUnary(ctx, req)
}

// StreamText calls dtkt.ai.v1beta1.TextService.StreamText.
func (c *textServiceClient) StreamText(ctx context.Context, req *connect.Request[v1beta1.StreamTextRequest]) (*connect.ServerStreamForClient[v1beta1.StreamTextResponse], error) {
	return c.streamText.CallServerStream(ctx, req)
}

// TextServiceHandler is an implementation of the dtkt.ai.v1beta1.TextService service.
type TextServiceHandler interface {
	// Generates text for the provided input using a specified model.
	GenerateText(context.Context, *connect.Request[v1beta1.GenerateTextRequest]) (*connect.Response[v1beta1.GenerateTextResponse], error)
	// Streams text for the provided input using a specified model.
	StreamText(context.Context, *connect.Request[v1beta1.StreamTextRequest], *connect.ServerStream[v1beta1.StreamTextResponse]) error
}

// NewTextServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTextServiceHandler(svc TextServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	textServiceMethods := v1beta1.File_dtkt_ai_v1beta1_services_proto.Services().ByName("TextService").Methods()
	textServiceGenerateTextHandler := connect.NewUnaryHandler(
		TextServiceGenerateTextProcedure,
		svc.GenerateText,
		connect.WithSchema(textServiceMethods.ByName("GenerateText")),
		connect.WithHandlerOptions(opts...),
	)
	textServiceStreamTextHandler := connect.NewServerStreamHandler(
		TextServiceStreamTextProcedure,
		svc.StreamText,
		connect.WithSchema(textServiceMethods.ByName("StreamText")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dtkt.ai.v1beta1.TextService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TextServiceGenerateTextProcedure:
			textServiceGenerateTextHandler.ServeHTTP(w, r)
		case TextServiceStreamTextProcedure:
			textServiceStreamTextHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTextServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTextServiceHandler struct{}

func (UnimplementedTextServiceHandler) GenerateText(context.Context, *connect.Request[v1beta1.GenerateTextRequest]) (*connect.Response[v1beta1.GenerateTextResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.ai.v1beta1.TextService.GenerateText is not implemented"))
}

func (UnimplementedTextServiceHandler) StreamText(context.Context, *connect.Request[v1beta1.StreamTextRequest], *connect.ServerStream[v1beta1.StreamTextResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.ai.v1beta1.TextService.StreamText is not implemented"))
}

// ObjectServiceClient is a client for the dtkt.ai.v1beta1.ObjectService service.
type ObjectServiceClient interface {
	// Generates an object for the provided input using a specified model.
	GenerateObject(context.Context, *connect.Request[v1beta1.GenerateObjectRequest]) (*connect.Response[v1beta1.GenerateObjectResponse], error)
	// Streams objects for the provided input using a specified model.
	StreamObjects(context.Context, *connect.Request[v1beta1.StreamObjectsRequest]) (*connect.ServerStreamForClient[v1beta1.StreamObjectsResponse], error)
}

// NewObjectServiceClient constructs a client for the dtkt.ai.v1beta1.ObjectService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewObjectServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ObjectServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	objectServiceMethods := v1beta1.File_dtkt_ai_v1beta1_services_proto.Services().ByName("ObjectService").Methods()
	return &objectServiceClient{
		generateObject: connect.NewClient[v1beta1.GenerateObjectRequest, v1beta1.GenerateObjectResponse](
			httpClient,
			baseURL+ObjectServiceGenerateObjectProcedure,
			connect.WithSchema(objectServiceMethods.ByName("GenerateObject")),
			connect.WithClientOptions(opts...),
		),
		streamObjects: connect.NewClient[v1beta1.StreamObjectsRequest, v1beta1.StreamObjectsResponse](
			httpClient,
			baseURL+ObjectServiceStreamObjectsProcedure,
			connect.WithSchema(objectServiceMethods.ByName("StreamObjects")),
			connect.WithClientOptions(opts...),
		),
	}
}

// objectServiceClient implements ObjectServiceClient.
type objectServiceClient struct {
	generateObject *connect.Client[v1beta1.GenerateObjectRequest, v1beta1.GenerateObjectResponse]
	streamObjects  *connect.Client[v1beta1.StreamObjectsRequest, v1beta1.StreamObjectsResponse]
}

// GenerateObject calls dtkt.ai.v1beta1.ObjectService.GenerateObject.
func (c *objectServiceClient) GenerateObject(ctx context.Context, req *connect.Request[v1beta1.GenerateObjectRequest]) (*connect.Response[v1beta1.GenerateObjectResponse], error) {
	return c.generateObject.CallUnary(ctx, req)
}

// StreamObjects calls dtkt.ai.v1beta1.ObjectService.StreamObjects.
func (c *objectServiceClient) StreamObjects(ctx context.Context, req *connect.Request[v1beta1.StreamObjectsRequest]) (*connect.ServerStreamForClient[v1beta1.StreamObjectsResponse], error) {
	return c.streamObjects.CallServerStream(ctx, req)
}

// ObjectServiceHandler is an implementation of the dtkt.ai.v1beta1.ObjectService service.
type ObjectServiceHandler interface {
	// Generates an object for the provided input using a specified model.
	GenerateObject(context.Context, *connect.Request[v1beta1.GenerateObjectRequest]) (*connect.Response[v1beta1.GenerateObjectResponse], error)
	// Streams objects for the provided input using a specified model.
	StreamObjects(context.Context, *connect.Request[v1beta1.StreamObjectsRequest], *connect.ServerStream[v1beta1.StreamObjectsResponse]) error
}

// NewObjectServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewObjectServiceHandler(svc ObjectServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	objectServiceMethods := v1beta1.File_dtkt_ai_v1beta1_services_proto.Services().ByName("ObjectService").Methods()
	objectServiceGenerateObjectHandler := connect.NewUnaryHandler(
		ObjectServiceGenerateObjectProcedure,
		svc.GenerateObject,
		connect.WithSchema(objectServiceMethods.ByName("GenerateObject")),
		connect.WithHandlerOptions(opts...),
	)
	objectServiceStreamObjectsHandler := connect.NewServerStreamHandler(
		ObjectServiceStreamObjectsProcedure,
		svc.StreamObjects,
		connect.WithSchema(objectServiceMethods.ByName("StreamObjects")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dtkt.ai.v1beta1.ObjectService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ObjectServiceGenerateObjectProcedure:
			objectServiceGenerateObjectHandler.ServeHTTP(w, r)
		case ObjectServiceStreamObjectsProcedure:
			objectServiceStreamObjectsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedObjectServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedObjectServiceHandler struct{}

func (UnimplementedObjectServiceHandler) GenerateObject(context.Context, *connect.Request[v1beta1.GenerateObjectRequest]) (*connect.Response[v1beta1.GenerateObjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.ai.v1beta1.ObjectService.GenerateObject is not implemented"))
}

func (UnimplementedObjectServiceHandler) StreamObjects(context.Context, *connect.Request[v1beta1.StreamObjectsRequest], *connect.ServerStream[v1beta1.StreamObjectsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.ai.v1beta1.ObjectService.StreamObjects is not implemented"))
}

// EmbeddingServiceClient is a client for the dtkt.ai.v1beta1.EmbeddingService service.
type EmbeddingServiceClient interface {
	// Retrieves a list of available embedding models.
	ListEmbeddingModels(context.Context, *connect.Request[v1beta1.ListEmbeddingModelsRequest]) (*connect.Response[v1beta1.ListEmbeddingModelsResponse], error)
	// Retrieves details of a specific embedding model by its ID.
	GetEmbeddingModel(context.Context, *connect.Request[v1beta1.GetEmbeddingModelRequest]) (*connect.Response[v1beta1.GetEmbeddingModelResponse], error)
	// Generates embeddings for the provided input text using a specified model.
	GenerateEmbeddings(context.Context, *connect.Request[v1beta1.GenerateEmbeddingsRequest]) (*connect.Response[v1beta1.GenerateEmbeddingsResponse], error)
}

// NewEmbeddingServiceClient constructs a client for the dtkt.ai.v1beta1.EmbeddingService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEmbeddingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EmbeddingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	embeddingServiceMethods := v1beta1.File_dtkt_ai_v1beta1_services_proto.Services().ByName("EmbeddingService").Methods()
	return &embeddingServiceClient{
		listEmbeddingModels: connect.NewClient[v1beta1.ListEmbeddingModelsRequest, v1beta1.ListEmbeddingModelsResponse](
			httpClient,
			baseURL+EmbeddingServiceListEmbeddingModelsProcedure,
			connect.WithSchema(embeddingServiceMethods.ByName("ListEmbeddingModels")),
			connect.WithClientOptions(opts...),
		),
		getEmbeddingModel: connect.NewClient[v1beta1.GetEmbeddingModelRequest, v1beta1.GetEmbeddingModelResponse](
			httpClient,
			baseURL+EmbeddingServiceGetEmbeddingModelProcedure,
			connect.WithSchema(embeddingServiceMethods.ByName("GetEmbeddingModel")),
			connect.WithClientOptions(opts...),
		),
		generateEmbeddings: connect.NewClient[v1beta1.GenerateEmbeddingsRequest, v1beta1.GenerateEmbeddingsResponse](
			httpClient,
			baseURL+EmbeddingServiceGenerateEmbeddingsProcedure,
			connect.WithSchema(embeddingServiceMethods.ByName("GenerateEmbeddings")),
			connect.WithClientOptions(opts...),
		),
	}
}

// embeddingServiceClient implements EmbeddingServiceClient.
type embeddingServiceClient struct {
	listEmbeddingModels *connect.Client[v1beta1.ListEmbeddingModelsRequest, v1beta1.ListEmbeddingModelsResponse]
	getEmbeddingModel   *connect.Client[v1beta1.GetEmbeddingModelRequest, v1beta1.GetEmbeddingModelResponse]
	generateEmbeddings  *connect.Client[v1beta1.GenerateEmbeddingsRequest, v1beta1.GenerateEmbeddingsResponse]
}

// ListEmbeddingModels calls dtkt.ai.v1beta1.EmbeddingService.ListEmbeddingModels.
func (c *embeddingServiceClient) ListEmbeddingModels(ctx context.Context, req *connect.Request[v1beta1.ListEmbeddingModelsRequest]) (*connect.Response[v1beta1.ListEmbeddingModelsResponse], error) {
	return c.listEmbeddingModels.CallUnary(ctx, req)
}

// GetEmbeddingModel calls dtkt.ai.v1beta1.EmbeddingService.GetEmbeddingModel.
func (c *embeddingServiceClient) GetEmbeddingModel(ctx context.Context, req *connect.Request[v1beta1.GetEmbeddingModelRequest]) (*connect.Response[v1beta1.GetEmbeddingModelResponse], error) {
	return c.getEmbeddingModel.CallUnary(ctx, req)
}

// GenerateEmbeddings calls dtkt.ai.v1beta1.EmbeddingService.GenerateEmbeddings.
func (c *embeddingServiceClient) GenerateEmbeddings(ctx context.Context, req *connect.Request[v1beta1.GenerateEmbeddingsRequest]) (*connect.Response[v1beta1.GenerateEmbeddingsResponse], error) {
	return c.generateEmbeddings.CallUnary(ctx, req)
}

// EmbeddingServiceHandler is an implementation of the dtkt.ai.v1beta1.EmbeddingService service.
type EmbeddingServiceHandler interface {
	// Retrieves a list of available embedding models.
	ListEmbeddingModels(context.Context, *connect.Request[v1beta1.ListEmbeddingModelsRequest]) (*connect.Response[v1beta1.ListEmbeddingModelsResponse], error)
	// Retrieves details of a specific embedding model by its ID.
	GetEmbeddingModel(context.Context, *connect.Request[v1beta1.GetEmbeddingModelRequest]) (*connect.Response[v1beta1.GetEmbeddingModelResponse], error)
	// Generates embeddings for the provided input text using a specified model.
	GenerateEmbeddings(context.Context, *connect.Request[v1beta1.GenerateEmbeddingsRequest]) (*connect.Response[v1beta1.GenerateEmbeddingsResponse], error)
}

// NewEmbeddingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEmbeddingServiceHandler(svc EmbeddingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	embeddingServiceMethods := v1beta1.File_dtkt_ai_v1beta1_services_proto.Services().ByName("EmbeddingService").Methods()
	embeddingServiceListEmbeddingModelsHandler := connect.NewUnaryHandler(
		EmbeddingServiceListEmbeddingModelsProcedure,
		svc.ListEmbeddingModels,
		connect.WithSchema(embeddingServiceMethods.ByName("ListEmbeddingModels")),
		connect.WithHandlerOptions(opts...),
	)
	embeddingServiceGetEmbeddingModelHandler := connect.NewUnaryHandler(
		EmbeddingServiceGetEmbeddingModelProcedure,
		svc.GetEmbeddingModel,
		connect.WithSchema(embeddingServiceMethods.ByName("GetEmbeddingModel")),
		connect.WithHandlerOptions(opts...),
	)
	embeddingServiceGenerateEmbeddingsHandler := connect.NewUnaryHandler(
		EmbeddingServiceGenerateEmbeddingsProcedure,
		svc.GenerateEmbeddings,
		connect.WithSchema(embeddingServiceMethods.ByName("GenerateEmbeddings")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dtkt.ai.v1beta1.EmbeddingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EmbeddingServiceListEmbeddingModelsProcedure:
			embeddingServiceListEmbeddingModelsHandler.ServeHTTP(w, r)
		case EmbeddingServiceGetEmbeddingModelProcedure:
			embeddingServiceGetEmbeddingModelHandler.ServeHTTP(w, r)
		case EmbeddingServiceGenerateEmbeddingsProcedure:
			embeddingServiceGenerateEmbeddingsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEmbeddingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEmbeddingServiceHandler struct{}

func (UnimplementedEmbeddingServiceHandler) ListEmbeddingModels(context.Context, *connect.Request[v1beta1.ListEmbeddingModelsRequest]) (*connect.Response[v1beta1.ListEmbeddingModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.ai.v1beta1.EmbeddingService.ListEmbeddingModels is not implemented"))
}

func (UnimplementedEmbeddingServiceHandler) GetEmbeddingModel(context.Context, *connect.Request[v1beta1.GetEmbeddingModelRequest]) (*connect.Response[v1beta1.GetEmbeddingModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.ai.v1beta1.EmbeddingService.GetEmbeddingModel is not implemented"))
}

func (UnimplementedEmbeddingServiceHandler) GenerateEmbeddings(context.Context, *connect.Request[v1beta1.GenerateEmbeddingsRequest]) (*connect.Response[v1beta1.GenerateEmbeddingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.ai.v1beta1.EmbeddingService.GenerateEmbeddings is not implemented"))
}

// ImageServiceClient is a client for the dtkt.ai.v1beta1.ImageService service.
type ImageServiceClient interface {
	// Generates an image for the provided input using a specified model.
	GenerateImage(context.Context, *connect.Request[v1beta1.GenerateImageRequest]) (*connect.Response[v1beta1.GenerateImageResponse], error)
	// Generates images for the provided input using a specified model.
	GenerateImages(context.Context, *connect.Request[v1beta1.GenerateImagesRequest]) (*connect.Response[v1beta1.GenerateImagesResponse], error)
	// Generate a batch of images for the provided input using a specified model.
	GenerateBatchImages(context.Context, *connect.Request[v1beta1.GenerateBatchImagesRequest]) (*connect.Response[v1beta1.GenerateBatchImagesResponse], error)
}

// NewImageServiceClient constructs a client for the dtkt.ai.v1beta1.ImageService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewImageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ImageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	imageServiceMethods := v1beta1.File_dtkt_ai_v1beta1_services_proto.Services().ByName("ImageService").Methods()
	return &imageServiceClient{
		generateImage: connect.NewClient[v1beta1.GenerateImageRequest, v1beta1.GenerateImageResponse](
			httpClient,
			baseURL+ImageServiceGenerateImageProcedure,
			connect.WithSchema(imageServiceMethods.ByName("GenerateImage")),
			connect.WithClientOptions(opts...),
		),
		generateImages: connect.NewClient[v1beta1.GenerateImagesRequest, v1beta1.GenerateImagesResponse](
			httpClient,
			baseURL+ImageServiceGenerateImagesProcedure,
			connect.WithSchema(imageServiceMethods.ByName("GenerateImages")),
			connect.WithClientOptions(opts...),
		),
		generateBatchImages: connect.NewClient[v1beta1.GenerateBatchImagesRequest, v1beta1.GenerateBatchImagesResponse](
			httpClient,
			baseURL+ImageServiceGenerateBatchImagesProcedure,
			connect.WithSchema(imageServiceMethods.ByName("GenerateBatchImages")),
			connect.WithClientOptions(opts...),
		),
	}
}

// imageServiceClient implements ImageServiceClient.
type imageServiceClient struct {
	generateImage       *connect.Client[v1beta1.GenerateImageRequest, v1beta1.GenerateImageResponse]
	generateImages      *connect.Client[v1beta1.GenerateImagesRequest, v1beta1.GenerateImagesResponse]
	generateBatchImages *connect.Client[v1beta1.GenerateBatchImagesRequest, v1beta1.GenerateBatchImagesResponse]
}

// GenerateImage calls dtkt.ai.v1beta1.ImageService.GenerateImage.
func (c *imageServiceClient) GenerateImage(ctx context.Context, req *connect.Request[v1beta1.GenerateImageRequest]) (*connect.Response[v1beta1.GenerateImageResponse], error) {
	return c.generateImage.CallUnary(ctx, req)
}

// GenerateImages calls dtkt.ai.v1beta1.ImageService.GenerateImages.
func (c *imageServiceClient) GenerateImages(ctx context.Context, req *connect.Request[v1beta1.GenerateImagesRequest]) (*connect.Response[v1beta1.GenerateImagesResponse], error) {
	return c.generateImages.CallUnary(ctx, req)
}

// GenerateBatchImages calls dtkt.ai.v1beta1.ImageService.GenerateBatchImages.
func (c *imageServiceClient) GenerateBatchImages(ctx context.Context, req *connect.Request[v1beta1.GenerateBatchImagesRequest]) (*connect.Response[v1beta1.GenerateBatchImagesResponse], error) {
	return c.generateBatchImages.CallUnary(ctx, req)
}

// ImageServiceHandler is an implementation of the dtkt.ai.v1beta1.ImageService service.
type ImageServiceHandler interface {
	// Generates an image for the provided input using a specified model.
	GenerateImage(context.Context, *connect.Request[v1beta1.GenerateImageRequest]) (*connect.Response[v1beta1.GenerateImageResponse], error)
	// Generates images for the provided input using a specified model.
	GenerateImages(context.Context, *connect.Request[v1beta1.GenerateImagesRequest]) (*connect.Response[v1beta1.GenerateImagesResponse], error)
	// Generate a batch of images for the provided input using a specified model.
	GenerateBatchImages(context.Context, *connect.Request[v1beta1.GenerateBatchImagesRequest]) (*connect.Response[v1beta1.GenerateBatchImagesResponse], error)
}

// NewImageServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewImageServiceHandler(svc ImageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	imageServiceMethods := v1beta1.File_dtkt_ai_v1beta1_services_proto.Services().ByName("ImageService").Methods()
	imageServiceGenerateImageHandler := connect.NewUnaryHandler(
		ImageServiceGenerateImageProcedure,
		svc.GenerateImage,
		connect.WithSchema(imageServiceMethods.ByName("GenerateImage")),
		connect.WithHandlerOptions(opts...),
	)
	imageServiceGenerateImagesHandler := connect.NewUnaryHandler(
		ImageServiceGenerateImagesProcedure,
		svc.GenerateImages,
		connect.WithSchema(imageServiceMethods.ByName("GenerateImages")),
		connect.WithHandlerOptions(opts...),
	)
	imageServiceGenerateBatchImagesHandler := connect.NewUnaryHandler(
		ImageServiceGenerateBatchImagesProcedure,
		svc.GenerateBatchImages,
		connect.WithSchema(imageServiceMethods.ByName("GenerateBatchImages")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dtkt.ai.v1beta1.ImageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ImageServiceGenerateImageProcedure:
			imageServiceGenerateImageHandler.ServeHTTP(w, r)
		case ImageServiceGenerateImagesProcedure:
			imageServiceGenerateImagesHandler.ServeHTTP(w, r)
		case ImageServiceGenerateBatchImagesProcedure:
			imageServiceGenerateBatchImagesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedImageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedImageServiceHandler struct{}

func (UnimplementedImageServiceHandler) GenerateImage(context.Context, *connect.Request[v1beta1.GenerateImageRequest]) (*connect.Response[v1beta1.GenerateImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.ai.v1beta1.ImageService.GenerateImage is not implemented"))
}

func (UnimplementedImageServiceHandler) GenerateImages(context.Context, *connect.Request[v1beta1.GenerateImagesRequest]) (*connect.Response[v1beta1.GenerateImagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.ai.v1beta1.ImageService.GenerateImages is not implemented"))
}

func (UnimplementedImageServiceHandler) GenerateBatchImages(context.Context, *connect.Request[v1beta1.GenerateBatchImagesRequest]) (*connect.Response[v1beta1.GenerateBatchImagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.ai.v1beta1.ImageService.GenerateBatchImages is not implemented"))
}

// TranscriptionServiceClient is a client for the dtkt.ai.v1beta1.TranscriptionService service.
type TranscriptionServiceClient interface {
	// Transcribes audio to text  for the provided input using a specified model.
	Transcribe(context.Context, *connect.Request[v1beta1.TranscribeRequest]) (*connect.Response[v1beta1.TranscribeResponse], error)
}

// NewTranscriptionServiceClient constructs a client for the dtkt.ai.v1beta1.TranscriptionService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTranscriptionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TranscriptionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	transcriptionServiceMethods := v1beta1.File_dtkt_ai_v1beta1_services_proto.Services().ByName("TranscriptionService").Methods()
	return &transcriptionServiceClient{
		transcribe: connect.NewClient[v1beta1.TranscribeRequest, v1beta1.TranscribeResponse](
			httpClient,
			baseURL+TranscriptionServiceTranscribeProcedure,
			connect.WithSchema(transcriptionServiceMethods.ByName("Transcribe")),
			connect.WithClientOptions(opts...),
		),
	}
}

// transcriptionServiceClient implements TranscriptionServiceClient.
type transcriptionServiceClient struct {
	transcribe *connect.Client[v1beta1.TranscribeRequest, v1beta1.TranscribeResponse]
}

// Transcribe calls dtkt.ai.v1beta1.TranscriptionService.Transcribe.
func (c *transcriptionServiceClient) Transcribe(ctx context.Context, req *connect.Request[v1beta1.TranscribeRequest]) (*connect.Response[v1beta1.TranscribeResponse], error) {
	return c.transcribe.CallUnary(ctx, req)
}

// TranscriptionServiceHandler is an implementation of the dtkt.ai.v1beta1.TranscriptionService
// service.
type TranscriptionServiceHandler interface {
	// Transcribes audio to text  for the provided input using a specified model.
	Transcribe(context.Context, *connect.Request[v1beta1.TranscribeRequest]) (*connect.Response[v1beta1.TranscribeResponse], error)
}

// NewTranscriptionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTranscriptionServiceHandler(svc TranscriptionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	transcriptionServiceMethods := v1beta1.File_dtkt_ai_v1beta1_services_proto.Services().ByName("TranscriptionService").Methods()
	transcriptionServiceTranscribeHandler := connect.NewUnaryHandler(
		TranscriptionServiceTranscribeProcedure,
		svc.Transcribe,
		connect.WithSchema(transcriptionServiceMethods.ByName("Transcribe")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dtkt.ai.v1beta1.TranscriptionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TranscriptionServiceTranscribeProcedure:
			transcriptionServiceTranscribeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTranscriptionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTranscriptionServiceHandler struct{}

func (UnimplementedTranscriptionServiceHandler) Transcribe(context.Context, *connect.Request[v1beta1.TranscribeRequest]) (*connect.Response[v1beta1.TranscribeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.ai.v1beta1.TranscriptionService.Transcribe is not implemented"))
}

// SpeechServiceClient is a client for the dtkt.ai.v1beta1.SpeechService service.
type SpeechServiceClient interface {
	// Generates speech for the provided text input using a specified model.
	GenerateSpeech(context.Context, *connect.Request[v1beta1.GenerateSpeechRequest]) (*connect.Response[v1beta1.GenerateSpeechResponse], error)
	// Streams speech for the provided text input using a specified model.
	StreamSpeech(context.Context, *connect.Request[v1beta1.StreamSpeechRequest]) (*connect.ServerStreamForClient[v1beta1.StreamSpeechResponse], error)
}

// NewSpeechServiceClient constructs a client for the dtkt.ai.v1beta1.SpeechService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSpeechServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SpeechServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	speechServiceMethods := v1beta1.File_dtkt_ai_v1beta1_services_proto.Services().ByName("SpeechService").Methods()
	return &speechServiceClient{
		generateSpeech: connect.NewClient[v1beta1.GenerateSpeechRequest, v1beta1.GenerateSpeechResponse](
			httpClient,
			baseURL+SpeechServiceGenerateSpeechProcedure,
			connect.WithSchema(speechServiceMethods.ByName("GenerateSpeech")),
			connect.WithClientOptions(opts...),
		),
		streamSpeech: connect.NewClient[v1beta1.StreamSpeechRequest, v1beta1.StreamSpeechResponse](
			httpClient,
			baseURL+SpeechServiceStreamSpeechProcedure,
			connect.WithSchema(speechServiceMethods.ByName("StreamSpeech")),
			connect.WithClientOptions(opts...),
		),
	}
}

// speechServiceClient implements SpeechServiceClient.
type speechServiceClient struct {
	generateSpeech *connect.Client[v1beta1.GenerateSpeechRequest, v1beta1.GenerateSpeechResponse]
	streamSpeech   *connect.Client[v1beta1.StreamSpeechRequest, v1beta1.StreamSpeechResponse]
}

// GenerateSpeech calls dtkt.ai.v1beta1.SpeechService.GenerateSpeech.
func (c *speechServiceClient) GenerateSpeech(ctx context.Context, req *connect.Request[v1beta1.GenerateSpeechRequest]) (*connect.Response[v1beta1.GenerateSpeechResponse], error) {
	return c.generateSpeech.CallUnary(ctx, req)
}

// StreamSpeech calls dtkt.ai.v1beta1.SpeechService.StreamSpeech.
func (c *speechServiceClient) StreamSpeech(ctx context.Context, req *connect.Request[v1beta1.StreamSpeechRequest]) (*connect.ServerStreamForClient[v1beta1.StreamSpeechResponse], error) {
	return c.streamSpeech.CallServerStream(ctx, req)
}

// SpeechServiceHandler is an implementation of the dtkt.ai.v1beta1.SpeechService service.
type SpeechServiceHandler interface {
	// Generates speech for the provided text input using a specified model.
	GenerateSpeech(context.Context, *connect.Request[v1beta1.GenerateSpeechRequest]) (*connect.Response[v1beta1.GenerateSpeechResponse], error)
	// Streams speech for the provided text input using a specified model.
	StreamSpeech(context.Context, *connect.Request[v1beta1.StreamSpeechRequest], *connect.ServerStream[v1beta1.StreamSpeechResponse]) error
}

// NewSpeechServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSpeechServiceHandler(svc SpeechServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	speechServiceMethods := v1beta1.File_dtkt_ai_v1beta1_services_proto.Services().ByName("SpeechService").Methods()
	speechServiceGenerateSpeechHandler := connect.NewUnaryHandler(
		SpeechServiceGenerateSpeechProcedure,
		svc.GenerateSpeech,
		connect.WithSchema(speechServiceMethods.ByName("GenerateSpeech")),
		connect.WithHandlerOptions(opts...),
	)
	speechServiceStreamSpeechHandler := connect.NewServerStreamHandler(
		SpeechServiceStreamSpeechProcedure,
		svc.StreamSpeech,
		connect.WithSchema(speechServiceMethods.ByName("StreamSpeech")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dtkt.ai.v1beta1.SpeechService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SpeechServiceGenerateSpeechProcedure:
			speechServiceGenerateSpeechHandler.ServeHTTP(w, r)
		case SpeechServiceStreamSpeechProcedure:
			speechServiceStreamSpeechHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSpeechServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSpeechServiceHandler struct{}

func (UnimplementedSpeechServiceHandler) GenerateSpeech(context.Context, *connect.Request[v1beta1.GenerateSpeechRequest]) (*connect.Response[v1beta1.GenerateSpeechResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.ai.v1beta1.SpeechService.GenerateSpeech is not implemented"))
}

func (UnimplementedSpeechServiceHandler) StreamSpeech(context.Context, *connect.Request[v1beta1.StreamSpeechRequest], *connect.ServerStream[v1beta1.StreamSpeechResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.ai.v1beta1.SpeechService.StreamSpeech is not implemented"))
}
