// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,valid_types=protovalidate_required"
// @generated from file dtkt/flow/v1beta1/type.proto (package dtkt.flow.v1beta1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { ListValue } from "../../../google/protobuf/struct_pb";
import { file_google_protobuf_struct } from "../../../google/protobuf/struct_pb";
import type { JsonObject, Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file dtkt/flow/v1beta1/type.proto.
 */
export const file_dtkt_flow_v1beta1_type: GenFile = /*@__PURE__*/
  fileDesc("ChxkdGt0L2Zsb3cvdjFiZXRhMS90eXBlLnByb3RvEhFkdGt0LmZsb3cudjFiZXRhMSI6CgRCb29sEhQKB2RlZmF1bHQYASABKAhIAIgBARIQCghudWxsYWJsZRgCIAEoCEIKCghfZGVmYXVsdCI7CgVCeXRlcxIUCgdkZWZhdWx0GAEgASgMSACIAQESEAoIbnVsbGFibGUYAiABKAhCCgoIX2RlZmF1bHQiPAoGRG91YmxlEhQKB2RlZmF1bHQYASABKAFIAIgBARIQCghudWxsYWJsZRgCIAEoCEIKCghfZGVmYXVsdCI7CgVGbG9hdBIUCgdkZWZhdWx0GAEgASgCSACIAQESEAoIbnVsbGFibGUYAiABKAhCCgoIX2RlZmF1bHQiOwoFSW50NjQSFAoHZGVmYXVsdBgBIAEoA0gAiAEBEhAKCG51bGxhYmxlGAIgASgIQgoKCF9kZWZhdWx0IjwKBlVpbnQ2NBIUCgdkZWZhdWx0GAEgASgESACIAQESEAoIbnVsbGFibGUYAiABKAhCCgoIX2RlZmF1bHQiOwoFSW50MzISFAoHZGVmYXVsdBgBIAEoBUgAiAEBEhAKCG51bGxhYmxlGAIgASgIQgoKCF9kZWZhdWx0IjwKBlVpbnQzMhIUCgdkZWZhdWx0GAEgASgNSACIAQESEAoIbnVsbGFibGUYAiABKAhCCgoIX2RlZmF1bHQiPAoGU3RyaW5nEhQKB2RlZmF1bHQYASABKAlIAIgBARIQCghudWxsYWJsZRgCIAEoCEIKCghfZGVmYXVsdCJgCgRMaXN0EhkKBWl0ZW1zGAEgASgJQgq6SAfIAQFyAhABEhAKCG51bGxhYmxlGAIgASgIEisKB2RlZmF1bHQYAyABKAsyGi5nb29nbGUucHJvdG9idWYuTGlzdFZhbHVlIp8BCgNNYXASQQoDa2V5GAEgASgJQjS6SDHYAQFyLFIEYm9vbFIFaW50MzJSBWludDY0UgZ1aW50MzJSBnVpbnQ2NFIGc3RyaW5nEhkKBXZhbHVlGAIgASgJQgq6SAfIAQFyAhABEhAKCG51bGxhYmxlGAMgASgIEigKB2RlZmF1bHQYBCABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0IncKB01lc3NhZ2USMAoEdHlwZRgBIAEoCUIiukgfyAEBchoyGF5bYS16QS1aXVthLXpBLVowLTlfLl0rJBIQCghudWxsYWJsZRgCIAEoCBIoCgdkZWZhdWx0GAMgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdELWAQoXcHJvdG8uZHRrdC5mbG93LnYxYmV0YTFCCVR5cGVQcm90b1ABWkpnaXRodWIuY29tL2RhdGFraXQtZGV2L2R0a3Qtc2RrL3Nkay1nby9wcm90by9kdGt0L2Zsb3cvdjFiZXRhMTtmbG93djFiZXRhMaICA0RGWKoCEUR0a3QuRmxvdy5WMWJldGExygIRRHRrdFxGbG93XFYxYmV0YTHiAh1EdGt0XEZsb3dcVjFiZXRhMVxHUEJNZXRhZGF0YeoCE0R0a3Q6OkZsb3c6OlYxYmV0YTFiBnByb3RvMw", [file_buf_validate_validate, file_google_protobuf_struct]);

/**
 * @generated from message dtkt.flow.v1beta1.Bool
 */
export type Bool = Message$1<"dtkt.flow.v1beta1.Bool"> & {
  /**
   * @generated from field: optional bool default = 1;
   */
  default?: boolean;

  /**
   * @generated from field: bool nullable = 2;
   */
  nullable: boolean;
};

export type BoolValid = Bool;

/**
 * Describes the message dtkt.flow.v1beta1.Bool.
 * Use `create(BoolSchema)` to create a new message.
 */
export const BoolSchema: GenMessage<Bool, {validType: BoolValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta1_type, 0);

/**
 * @generated from message dtkt.flow.v1beta1.Bytes
 */
export type Bytes = Message$1<"dtkt.flow.v1beta1.Bytes"> & {
  /**
   * @generated from field: optional bytes default = 1;
   */
  default?: Uint8Array;

  /**
   * @generated from field: bool nullable = 2;
   */
  nullable: boolean;
};

export type BytesValid = Bytes;

/**
 * Describes the message dtkt.flow.v1beta1.Bytes.
 * Use `create(BytesSchema)` to create a new message.
 */
export const BytesSchema: GenMessage<Bytes, {validType: BytesValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta1_type, 1);

/**
 * @generated from message dtkt.flow.v1beta1.Double
 */
export type Double = Message$1<"dtkt.flow.v1beta1.Double"> & {
  /**
   * @generated from field: optional double default = 1;
   */
  default?: number;

  /**
   * @generated from field: bool nullable = 2;
   */
  nullable: boolean;
};

export type DoubleValid = Double;

/**
 * Describes the message dtkt.flow.v1beta1.Double.
 * Use `create(DoubleSchema)` to create a new message.
 */
export const DoubleSchema: GenMessage<Double, {validType: DoubleValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta1_type, 2);

/**
 * @generated from message dtkt.flow.v1beta1.Float
 */
export type Float = Message$1<"dtkt.flow.v1beta1.Float"> & {
  /**
   * @generated from field: optional float default = 1;
   */
  default?: number;

  /**
   * @generated from field: bool nullable = 2;
   */
  nullable: boolean;
};

export type FloatValid = Float;

/**
 * Describes the message dtkt.flow.v1beta1.Float.
 * Use `create(FloatSchema)` to create a new message.
 */
export const FloatSchema: GenMessage<Float, {validType: FloatValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta1_type, 3);

/**
 * @generated from message dtkt.flow.v1beta1.Int64
 */
export type Int64 = Message$1<"dtkt.flow.v1beta1.Int64"> & {
  /**
   * @generated from field: optional int64 default = 1;
   */
  default?: bigint;

  /**
   * @generated from field: bool nullable = 2;
   */
  nullable: boolean;
};

export type Int64Valid = Int64;

/**
 * Describes the message dtkt.flow.v1beta1.Int64.
 * Use `create(Int64Schema)` to create a new message.
 */
export const Int64Schema: GenMessage<Int64, {validType: Int64Valid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta1_type, 4);

/**
 * @generated from message dtkt.flow.v1beta1.Uint64
 */
export type Uint64 = Message$1<"dtkt.flow.v1beta1.Uint64"> & {
  /**
   * @generated from field: optional uint64 default = 1;
   */
  default?: bigint;

  /**
   * @generated from field: bool nullable = 2;
   */
  nullable: boolean;
};

export type Uint64Valid = Uint64;

/**
 * Describes the message dtkt.flow.v1beta1.Uint64.
 * Use `create(Uint64Schema)` to create a new message.
 */
export const Uint64Schema: GenMessage<Uint64, {validType: Uint64Valid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta1_type, 5);

/**
 * @generated from message dtkt.flow.v1beta1.Int32
 */
export type Int32 = Message$1<"dtkt.flow.v1beta1.Int32"> & {
  /**
   * @generated from field: optional int32 default = 1;
   */
  default?: number;

  /**
   * @generated from field: bool nullable = 2;
   */
  nullable: boolean;
};

export type Int32Valid = Int32;

/**
 * Describes the message dtkt.flow.v1beta1.Int32.
 * Use `create(Int32Schema)` to create a new message.
 */
export const Int32Schema: GenMessage<Int32, {validType: Int32Valid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta1_type, 6);

/**
 * @generated from message dtkt.flow.v1beta1.Uint32
 */
export type Uint32 = Message$1<"dtkt.flow.v1beta1.Uint32"> & {
  /**
   * @generated from field: optional uint32 default = 1;
   */
  default?: number;

  /**
   * @generated from field: bool nullable = 2;
   */
  nullable: boolean;
};

export type Uint32Valid = Uint32;

/**
 * Describes the message dtkt.flow.v1beta1.Uint32.
 * Use `create(Uint32Schema)` to create a new message.
 */
export const Uint32Schema: GenMessage<Uint32, {validType: Uint32Valid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta1_type, 7);

/**
 * @generated from message dtkt.flow.v1beta1.String
 */
export type String = Message$1<"dtkt.flow.v1beta1.String"> & {
  /**
   * @generated from field: optional string default = 1;
   */
  default?: string;

  /**
   * @generated from field: bool nullable = 2;
   */
  nullable: boolean;
};

export type StringValid = String;

/**
 * Describes the message dtkt.flow.v1beta1.String.
 * Use `create(StringSchema)` to create a new message.
 */
export const StringSchema: GenMessage<String, {validType: StringValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta1_type, 8);

/**
 * @generated from message dtkt.flow.v1beta1.List
 */
export type List = Message$1<"dtkt.flow.v1beta1.List"> & {
  /**
   * Type of list items: scalar type, nested list/map, or message type
   *
   * @generated from field: string items = 1;
   */
  items: string;

  /**
   * @generated from field: bool nullable = 2;
   */
  nullable: boolean;

  /**
   * @generated from field: google.protobuf.ListValue default = 3;
   */
  default?: ListValue;
};

/**
 * @generated from message dtkt.flow.v1beta1.List
 */
export type ListValid = Message$1<"dtkt.flow.v1beta1.List"> & {
  /**
   * Type of list items: scalar type, nested list/map, or message type
   *
   * @generated from field: string items = 1;
   */
  items: string;

  /**
   * @generated from field: bool nullable = 2;
   */
  nullable: boolean;

  /**
   * @generated from field: google.protobuf.ListValue default = 3;
   */
  default?: ListValue;
};

/**
 * Describes the message dtkt.flow.v1beta1.List.
 * Use `create(ListSchema)` to create a new message.
 */
export const ListSchema: GenMessage<List, {validType: ListValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta1_type, 9);

/**
 * @generated from message dtkt.flow.v1beta1.Map
 */
export type Map = Message$1<"dtkt.flow.v1beta1.Map"> & {
  /**
   * Key type: bool, int32, int64, uint32, uint64, or string (default)
   *
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * Value type: scalar type, nested list/map, or message type
   *
   * @generated from field: string value = 2;
   */
  value: string;

  /**
   * @generated from field: bool nullable = 3;
   */
  nullable: boolean;

  /**
   * @generated from field: google.protobuf.Struct default = 4;
   */
  default?: JsonObject;
};

/**
 * @generated from message dtkt.flow.v1beta1.Map
 */
export type MapValid = Message$1<"dtkt.flow.v1beta1.Map"> & {
  /**
   * Key type: bool, int32, int64, uint32, uint64, or string (default)
   *
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * Value type: scalar type, nested list/map, or message type
   *
   * @generated from field: string value = 2;
   */
  value: string;

  /**
   * @generated from field: bool nullable = 3;
   */
  nullable: boolean;

  /**
   * @generated from field: google.protobuf.Struct default = 4;
   */
  default?: JsonObject;
};

/**
 * Describes the message dtkt.flow.v1beta1.Map.
 * Use `create(MapSchema)` to create a new message.
 */
export const MapSchema: GenMessage<Map, {validType: MapValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta1_type, 10);

/**
 * Proto message type
 *
 * @generated from message dtkt.flow.v1beta1.Message
 */
export type Message = Message$1<"dtkt.flow.v1beta1.Message"> & {
  /**
   * Fully qualified message name: "google.protobuf.Struct", "google.protobuf.Timestamp", etc.
   *
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: bool nullable = 2;
   */
  nullable: boolean;

  /**
   * @generated from field: google.protobuf.Struct default = 3;
   */
  default?: JsonObject;
};

/**
 * Proto message type
 *
 * @generated from message dtkt.flow.v1beta1.Message
 */
export type MessageValid = Message$1<"dtkt.flow.v1beta1.Message"> & {
  /**
   * Fully qualified message name: "google.protobuf.Struct", "google.protobuf.Timestamp", etc.
   *
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: bool nullable = 2;
   */
  nullable: boolean;

  /**
   * @generated from field: google.protobuf.Struct default = 3;
   */
  default?: JsonObject;
};

/**
 * Describes the message dtkt.flow.v1beta1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema: GenMessage<Message, {validType: MessageValid}> = /*@__PURE__*/
  messageDesc(file_dtkt_flow_v1beta1_type, 11);

