// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file dtkt/catalog/v1beta2/catalog.proto (package dtkt.catalog.v1beta2, syntax proto3)
/* eslint-disable */

import { CatalogService } from "./catalog_pb";

/**
 * Create a catalog.
 *
 * @generated from rpc dtkt.catalog.v1beta2.CatalogService.CreateCatalog
 */
export const createCatalog = CatalogService.method.createCatalog;

/**
 * Delete a catalog.
 *
 * @generated from rpc dtkt.catalog.v1beta2.CatalogService.DeleteCatalog
 */
export const deleteCatalog = CatalogService.method.deleteCatalog;

/**
 * Get a catalog.
 *
 * @generated from rpc dtkt.catalog.v1beta2.CatalogService.GetCatalog
 */
export const getCatalog = CatalogService.method.getCatalog;

/**
 * List catalogs.
 *
 * @generated from rpc dtkt.catalog.v1beta2.CatalogService.ListCatalogs
 */
export const listCatalogs = CatalogService.method.listCatalogs;

/**
 * Update a catalog.
 *
 * @generated from rpc dtkt.catalog.v1beta2.CatalogService.UpdateCatalog
 */
export const updateCatalog = CatalogService.method.updateCatalog;
