// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: dtkt/geo/v1beta1/services.proto

package geov1beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeoService_ListGeoSources_FullMethodName = "/dtkt.geo.v1beta1.GeoService/ListGeoSources"
	GeoService_StreamGeoJson_FullMethodName  = "/dtkt.geo.v1beta1.GeoService/StreamGeoJson"
)

// GeoServiceClient is the client API for GeoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GeoService provides operations for managing geospatial data.
type GeoServiceClient interface {
	// Lists GeoSource results for given request.
	ListGeoSources(ctx context.Context, in *ListGeoSourcesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListGeoSourcesResponse], error)
	// Streams GeoJson results for given request.
	StreamGeoJson(ctx context.Context, in *StreamGeoJsonRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamGeoJsonResponse], error)
}

type geoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeoServiceClient(cc grpc.ClientConnInterface) GeoServiceClient {
	return &geoServiceClient{cc}
}

func (c *geoServiceClient) ListGeoSources(ctx context.Context, in *ListGeoSourcesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListGeoSourcesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GeoService_ServiceDesc.Streams[0], GeoService_ListGeoSources_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListGeoSourcesRequest, ListGeoSourcesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GeoService_ListGeoSourcesClient = grpc.ServerStreamingClient[ListGeoSourcesResponse]

func (c *geoServiceClient) StreamGeoJson(ctx context.Context, in *StreamGeoJsonRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamGeoJsonResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GeoService_ServiceDesc.Streams[1], GeoService_StreamGeoJson_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamGeoJsonRequest, StreamGeoJsonResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GeoService_StreamGeoJsonClient = grpc.ServerStreamingClient[StreamGeoJsonResponse]

// GeoServiceServer is the server API for GeoService service.
// All implementations must embed UnimplementedGeoServiceServer
// for forward compatibility.
//
// GeoService provides operations for managing geospatial data.
type GeoServiceServer interface {
	// Lists GeoSource results for given request.
	ListGeoSources(*ListGeoSourcesRequest, grpc.ServerStreamingServer[ListGeoSourcesResponse]) error
	// Streams GeoJson results for given request.
	StreamGeoJson(*StreamGeoJsonRequest, grpc.ServerStreamingServer[StreamGeoJsonResponse]) error
	mustEmbedUnimplementedGeoServiceServer()
}

// UnimplementedGeoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeoServiceServer struct{}

func (UnimplementedGeoServiceServer) ListGeoSources(*ListGeoSourcesRequest, grpc.ServerStreamingServer[ListGeoSourcesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ListGeoSources not implemented")
}
func (UnimplementedGeoServiceServer) StreamGeoJson(*StreamGeoJsonRequest, grpc.ServerStreamingServer[StreamGeoJsonResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamGeoJson not implemented")
}
func (UnimplementedGeoServiceServer) mustEmbedUnimplementedGeoServiceServer() {}
func (UnimplementedGeoServiceServer) testEmbeddedByValue()                    {}

// UnsafeGeoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeoServiceServer will
// result in compilation errors.
type UnsafeGeoServiceServer interface {
	mustEmbedUnimplementedGeoServiceServer()
}

func RegisterGeoServiceServer(s grpc.ServiceRegistrar, srv GeoServiceServer) {
	// If the following call pancis, it indicates UnimplementedGeoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeoService_ServiceDesc, srv)
}

func _GeoService_ListGeoSources_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListGeoSourcesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GeoServiceServer).ListGeoSources(m, &grpc.GenericServerStream[ListGeoSourcesRequest, ListGeoSourcesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GeoService_ListGeoSourcesServer = grpc.ServerStreamingServer[ListGeoSourcesResponse]

func _GeoService_StreamGeoJson_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamGeoJsonRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GeoServiceServer).StreamGeoJson(m, &grpc.GenericServerStream[StreamGeoJsonRequest, StreamGeoJsonResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GeoService_StreamGeoJsonServer = grpc.ServerStreamingServer[StreamGeoJsonResponse]

// GeoService_ServiceDesc is the grpc.ServiceDesc for GeoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dtkt.geo.v1beta1.GeoService",
	HandlerType: (*GeoServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListGeoSources",
			Handler:       _GeoService_ListGeoSources_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamGeoJson",
			Handler:       _GeoService_StreamGeoJson_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dtkt/geo/v1beta1/services.proto",
}
