// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: dtkt/email/v1beta1/messages.proto

package emailv1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TemplateLanguage int32

const (
	TemplateLanguage_TEMPLATE_LANGUAGE_UNSPECIFIED TemplateLanguage = 0
	TemplateLanguage_TEMPLATE_LANGUAGE_GO_TEMPLATE TemplateLanguage = 1 // https://golang.org/pkg/text/template and https://pkg.go.dev/html/template
	TemplateLanguage_TEMPLATE_LANGUAGE_MUSTACHIO   TemplateLanguage = 2 // https://postmarkapp.com/support/article/1077-template-syntax
)

// Enum value maps for TemplateLanguage.
var (
	TemplateLanguage_name = map[int32]string{
		0: "TEMPLATE_LANGUAGE_UNSPECIFIED",
		1: "TEMPLATE_LANGUAGE_GO_TEMPLATE",
		2: "TEMPLATE_LANGUAGE_MUSTACHIO",
	}
	TemplateLanguage_value = map[string]int32{
		"TEMPLATE_LANGUAGE_UNSPECIFIED": 0,
		"TEMPLATE_LANGUAGE_GO_TEMPLATE": 1,
		"TEMPLATE_LANGUAGE_MUSTACHIO":   2,
	}
)

func (x TemplateLanguage) Enum() *TemplateLanguage {
	p := new(TemplateLanguage)
	*p = x
	return p
}

func (x TemplateLanguage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateLanguage) Descriptor() protoreflect.EnumDescriptor {
	return file_dtkt_email_v1beta1_messages_proto_enumTypes[0].Descriptor()
}

func (TemplateLanguage) Type() protoreflect.EnumType {
	return &file_dtkt_email_v1beta1_messages_proto_enumTypes[0]
}

func (x TemplateLanguage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateLanguage.Descriptor instead.
func (TemplateLanguage) EnumDescriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{0}
}

type EmailAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The email address.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// The name associated with the email address.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailAddress) Reset() {
	*x = EmailAddress{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailAddress) ProtoMessage() {}

func (x *EmailAddress) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailAddress.ProtoReflect.Descriptor instead.
func (*EmailAddress) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *EmailAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EmailAddress) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EmailSendStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailSendStatus) Reset() {
	*x = EmailSendStatus{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailSendStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailSendStatus) ProtoMessage() {}

func (x *EmailSendStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailSendStatus.ProtoReflect.Descriptor instead.
func (*EmailSendStatus) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *EmailSendStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmailSendStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmailSendStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Represents an email message.
type Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *EmailAddress          `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	ReplyTo       *EmailAddress          `protobuf:"bytes,2,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	To            []*EmailAddress        `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	Cc            []*EmailAddress        `protobuf:"bytes,4,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc           []*EmailAddress        `protobuf:"bytes,5,rep,name=bcc,proto3" json:"bcc,omitempty"`
	ReturnPath    *EmailAddress          `protobuf:"bytes,6,opt,name=return_path,json=returnPath,proto3" json:"return_path,omitempty"`
	Subject       string                 `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	TextBody      string                 `protobuf:"bytes,8,opt,name=text_body,json=textBody,proto3" json:"text_body,omitempty"`
	HtmlBody      string                 `protobuf:"bytes,9,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Email) GetFrom() *EmailAddress {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Email) GetReplyTo() *EmailAddress {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

func (x *Email) GetTo() []*EmailAddress {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Email) GetCc() []*EmailAddress {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *Email) GetBcc() []*EmailAddress {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *Email) GetReturnPath() *EmailAddress {
	if x != nil {
		return x.ReturnPath
	}
	return nil
}

func (x *Email) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Email) GetTextBody() string {
	if x != nil {
		return x.TextBody
	}
	return ""
}

func (x *Email) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

// Represents an email template.
type EmailTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Language      TemplateLanguage       `protobuf:"varint,2,opt,name=language,proto3,enum=dtkt.email.v1beta1.TemplateLanguage" json:"language,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	TextBody      string                 `protobuf:"bytes,4,opt,name=text_body,json=textBody,proto3" json:"text_body,omitempty"`
	HtmlBody      string                 `protobuf:"bytes,5,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailTemplate) Reset() {
	*x = EmailTemplate{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTemplate) ProtoMessage() {}

func (x *EmailTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTemplate.ProtoReflect.Descriptor instead.
func (*EmailTemplate) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *EmailTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmailTemplate) GetLanguage() TemplateLanguage {
	if x != nil {
		return x.Language
	}
	return TemplateLanguage_TEMPLATE_LANGUAGE_UNSPECIFIED
}

func (x *EmailTemplate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailTemplate) GetTextBody() string {
	if x != nil {
		return x.TextBody
	}
	return ""
}

func (x *EmailTemplate) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

// Represents an email message.
type EmailWithTemplate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	From           *EmailAddress          `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	ReplyTo        *EmailAddress          `protobuf:"bytes,2,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	To             []*EmailAddress        `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	Cc             []*EmailAddress        `protobuf:"bytes,4,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc            []*EmailAddress        `protobuf:"bytes,5,rep,name=bcc,proto3" json:"bcc,omitempty"`
	ReturnPath     *EmailAddress          `protobuf:"bytes,6,opt,name=return_path,json=returnPath,proto3" json:"return_path,omitempty"`
	TemplateId     string                 `protobuf:"bytes,7,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	TemplateParams map[string]string      `protobuf:"bytes,8,rep,name=template_params,json=templateParams,proto3" json:"template_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EmailWithTemplate) Reset() {
	*x = EmailWithTemplate{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailWithTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailWithTemplate) ProtoMessage() {}

func (x *EmailWithTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailWithTemplate.ProtoReflect.Descriptor instead.
func (*EmailWithTemplate) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *EmailWithTemplate) GetFrom() *EmailAddress {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EmailWithTemplate) GetReplyTo() *EmailAddress {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

func (x *EmailWithTemplate) GetTo() []*EmailAddress {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EmailWithTemplate) GetCc() []*EmailAddress {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *EmailWithTemplate) GetBcc() []*EmailAddress {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *EmailWithTemplate) GetReturnPath() *EmailAddress {
	if x != nil {
		return x.ReturnPath
	}
	return nil
}

func (x *EmailWithTemplate) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *EmailWithTemplate) GetTemplateParams() map[string]string {
	if x != nil {
		return x.TemplateParams
	}
	return nil
}

// Represents an email sending request.
type SendEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The email to be sent.
	Email         *Email `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *SendEmailRequest) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

// Represents an email sending response.
type SendEmailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The email sending status.
	SendStatus    *EmailSendStatus `protobuf:"bytes,1,opt,name=send_status,json=sendStatus,proto3" json:"send_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *SendEmailResponse) GetSendStatus() *EmailSendStatus {
	if x != nil {
		return x.SendStatus
	}
	return nil
}

// Represents a stream of email sending requests.
type SendEmailsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The email to be sent.
	Email         *Email `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailsRequest) Reset() {
	*x = SendEmailsRequest{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailsRequest) ProtoMessage() {}

func (x *SendEmailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailsRequest.ProtoReflect.Descriptor instead.
func (*SendEmailsRequest) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *SendEmailsRequest) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

// Represents a stream of email sending responses.
type SendEmailsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The email sending status.
	SendStatus    *EmailSendStatus `protobuf:"bytes,1,opt,name=send_status,json=sendStatus,proto3" json:"send_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailsResponse) Reset() {
	*x = SendEmailsResponse{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailsResponse) ProtoMessage() {}

func (x *SendEmailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailsResponse.ProtoReflect.Descriptor instead.
func (*SendEmailsResponse) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *SendEmailsResponse) GetSendStatus() *EmailSendStatus {
	if x != nil {
		return x.SendStatus
	}
	return nil
}

// Represents a batch email sending request.
type SendBatchEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of emails to be sent.
	Emails        []*Email `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBatchEmailRequest) Reset() {
	*x = SendBatchEmailRequest{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBatchEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchEmailRequest) ProtoMessage() {}

func (x *SendBatchEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchEmailRequest.ProtoReflect.Descriptor instead.
func (*SendBatchEmailRequest) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *SendBatchEmailRequest) GetEmails() []*Email {
	if x != nil {
		return x.Emails
	}
	return nil
}

// Represents a batch email sending response.
type SendBatchEmailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of email sending statuses.
	SendStatus    []*EmailSendStatus `protobuf:"bytes,1,rep,name=send_status,json=sendStatus,proto3" json:"send_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBatchEmailResponse) Reset() {
	*x = SendBatchEmailResponse{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBatchEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchEmailResponse) ProtoMessage() {}

func (x *SendBatchEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchEmailResponse.ProtoReflect.Descriptor instead.
func (*SendBatchEmailResponse) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *SendBatchEmailResponse) GetSendStatus() []*EmailSendStatus {
	if x != nil {
		return x.SendStatus
	}
	return nil
}

// Represents an email sending request sent with a template.
type SendEmailWithTemplateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The email to be sent.
	Email         *EmailWithTemplate `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailWithTemplateRequest) Reset() {
	*x = SendEmailWithTemplateRequest{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailWithTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailWithTemplateRequest) ProtoMessage() {}

func (x *SendEmailWithTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailWithTemplateRequest.ProtoReflect.Descriptor instead.
func (*SendEmailWithTemplateRequest) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *SendEmailWithTemplateRequest) GetEmail() *EmailWithTemplate {
	if x != nil {
		return x.Email
	}
	return nil
}

// Represents an email sending response sent with a template.
type SendEmailWithTemplateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The email sending status.
	SendStatus    *EmailSendStatus `protobuf:"bytes,1,opt,name=send_status,json=sendStatus,proto3" json:"send_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailWithTemplateResponse) Reset() {
	*x = SendEmailWithTemplateResponse{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailWithTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailWithTemplateResponse) ProtoMessage() {}

func (x *SendEmailWithTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailWithTemplateResponse.ProtoReflect.Descriptor instead.
func (*SendEmailWithTemplateResponse) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *SendEmailWithTemplateResponse) GetSendStatus() *EmailSendStatus {
	if x != nil {
		return x.SendStatus
	}
	return nil
}

// Represents a stream of email sending requests sent with a template.
type SendEmailsWithTemplateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The email to be sent.
	Email         *EmailWithTemplate `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailsWithTemplateRequest) Reset() {
	*x = SendEmailsWithTemplateRequest{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailsWithTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailsWithTemplateRequest) ProtoMessage() {}

func (x *SendEmailsWithTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailsWithTemplateRequest.ProtoReflect.Descriptor instead.
func (*SendEmailsWithTemplateRequest) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *SendEmailsWithTemplateRequest) GetEmail() *EmailWithTemplate {
	if x != nil {
		return x.Email
	}
	return nil
}

// Represents a stream of email sending responses sent with a template.
type SendEmailsWithTemplateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The email sending status.
	SendStatus    *EmailSendStatus `protobuf:"bytes,1,opt,name=send_status,json=sendStatus,proto3" json:"send_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailsWithTemplateResponse) Reset() {
	*x = SendEmailsWithTemplateResponse{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailsWithTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailsWithTemplateResponse) ProtoMessage() {}

func (x *SendEmailsWithTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailsWithTemplateResponse.ProtoReflect.Descriptor instead.
func (*SendEmailsWithTemplateResponse) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *SendEmailsWithTemplateResponse) GetSendStatus() *EmailSendStatus {
	if x != nil {
		return x.SendStatus
	}
	return nil
}

// Represents a batch email sending request sent with a template.
type SendBatchEmailWithTemplateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of emails to be sent.
	Emails        []*EmailWithTemplate `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBatchEmailWithTemplateRequest) Reset() {
	*x = SendBatchEmailWithTemplateRequest{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBatchEmailWithTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchEmailWithTemplateRequest) ProtoMessage() {}

func (x *SendBatchEmailWithTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchEmailWithTemplateRequest.ProtoReflect.Descriptor instead.
func (*SendBatchEmailWithTemplateRequest) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *SendBatchEmailWithTemplateRequest) GetEmails() []*EmailWithTemplate {
	if x != nil {
		return x.Emails
	}
	return nil
}

// Represents a batch email sending response sent with a template.
type SendBatchEmailWithTemplateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of email sending statuses.
	SendStatus    []*EmailSendStatus `protobuf:"bytes,1,rep,name=send_status,json=sendStatus,proto3" json:"send_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBatchEmailWithTemplateResponse) Reset() {
	*x = SendBatchEmailWithTemplateResponse{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBatchEmailWithTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchEmailWithTemplateResponse) ProtoMessage() {}

func (x *SendBatchEmailWithTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchEmailWithTemplateResponse.ProtoReflect.Descriptor instead.
func (*SendBatchEmailWithTemplateResponse) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{16}
}

func (x *SendBatchEmailWithTemplateResponse) GetSendStatus() []*EmailSendStatus {
	if x != nil {
		return x.SendStatus
	}
	return nil
}

// Represents a request to get an email template by ID.
type GetEmailTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailTemplateRequest) Reset() {
	*x = GetEmailTemplateRequest{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailTemplateRequest) ProtoMessage() {}

func (x *GetEmailTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetEmailTemplateRequest) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{17}
}

func (x *GetEmailTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Represents a response to get an email template by ID.
type GetEmailTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *EmailTemplate         `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailTemplateResponse) Reset() {
	*x = GetEmailTemplateResponse{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailTemplateResponse) ProtoMessage() {}

func (x *GetEmailTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailTemplateResponse.ProtoReflect.Descriptor instead.
func (*GetEmailTemplateResponse) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{18}
}

func (x *GetEmailTemplateResponse) GetTemplate() *EmailTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

// Represents a request to list email templates.
type ListEmailTemplatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of email templates to return. The service may return fewer than
	// this value.
	// If unspecified, at most 50 templates will be returned.
	// The maximum value is 1000; values above 1000 will be coerced to 1000.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token, received from a previous `ListEmailTemplates` call.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to `ListEmailTemplates` must match
	// the call that provided the page token.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailTemplatesRequest) Reset() {
	*x = ListEmailTemplatesRequest{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailTemplatesRequest) ProtoMessage() {}

func (x *ListEmailTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListEmailTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{19}
}

func (x *ListEmailTemplatesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEmailTemplatesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Represents a response to list email templates.
type ListEmailTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*EmailTemplate       `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailTemplatesResponse) Reset() {
	*x = ListEmailTemplatesResponse{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailTemplatesResponse) ProtoMessage() {}

func (x *ListEmailTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListEmailTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{20}
}

func (x *ListEmailTemplatesResponse) GetTemplates() []*EmailTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListEmailTemplatesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Represents a request to create an email template.
type CreateEmailTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *EmailTemplate         `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailTemplateRequest) Reset() {
	*x = CreateEmailTemplateRequest{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailTemplateRequest) ProtoMessage() {}

func (x *CreateEmailTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateEmailTemplateRequest) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{21}
}

func (x *CreateEmailTemplateRequest) GetTemplate() *EmailTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

// Represents a response to create an email template.
type CreateEmailTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *EmailTemplate         `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailTemplateResponse) Reset() {
	*x = CreateEmailTemplateResponse{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailTemplateResponse) ProtoMessage() {}

func (x *CreateEmailTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailTemplateResponse.ProtoReflect.Descriptor instead.
func (*CreateEmailTemplateResponse) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{22}
}

func (x *CreateEmailTemplateResponse) GetTemplate() *EmailTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

// Represents a request to update an email template.
type UpdateEmailTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Template      *EmailTemplate         `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailTemplateRequest) Reset() {
	*x = UpdateEmailTemplateRequest{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailTemplateRequest) ProtoMessage() {}

func (x *UpdateEmailTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailTemplateRequest) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateEmailTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEmailTemplateRequest) GetTemplate() *EmailTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

// Represents a response to update an email template.
type UpdateEmailTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *EmailTemplate         `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailTemplateResponse) Reset() {
	*x = UpdateEmailTemplateResponse{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailTemplateResponse) ProtoMessage() {}

func (x *UpdateEmailTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailTemplateResponse.ProtoReflect.Descriptor instead.
func (*UpdateEmailTemplateResponse) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateEmailTemplateResponse) GetTemplate() *EmailTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

// Represents a request to delete an email template.
type DeleteEmailTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmailTemplateRequest) Reset() {
	*x = DeleteEmailTemplateRequest{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmailTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmailTemplateRequest) ProtoMessage() {}

func (x *DeleteEmailTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmailTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmailTemplateRequest) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteEmailTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Represents a response to delete an email template.
type DeleteEmailTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmailTemplateResponse) Reset() {
	*x = DeleteEmailTemplateResponse{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmailTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmailTemplateResponse) ProtoMessage() {}

func (x *DeleteEmailTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmailTemplateResponse.ProtoReflect.Descriptor instead.
func (*DeleteEmailTemplateResponse) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteEmailTemplateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Represents a received Email
type ReceivedEmail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	At            string                 `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	Email         *Email                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceivedEmail) Reset() {
	*x = ReceivedEmail{}
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivedEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedEmail) ProtoMessage() {}

func (x *ReceivedEmail) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_email_v1beta1_messages_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedEmail.ProtoReflect.Descriptor instead.
func (*ReceivedEmail) Descriptor() ([]byte, []int) {
	return file_dtkt_email_v1beta1_messages_proto_rawDescGZIP(), []int{27}
}

func (x *ReceivedEmail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReceivedEmail) GetAt() string {
	if x != nil {
		return x.At
	}
	return ""
}

func (x *ReceivedEmail) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

var File_dtkt_email_v1beta1_messages_proto protoreflect.FileDescriptor

const file_dtkt_email_v1beta1_messages_proto_rawDesc = "" +
	"\n" +
	"!dtkt/email/v1beta1/messages.proto\x12\x12dtkt.email.v1beta1\"<\n" +
	"\fEmailAddress\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"Q\n" +
	"\x0fEmailSendStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xa9\x03\n" +
	"\x05Email\x124\n" +
	"\x04from\x18\x01 \x01(\v2 .dtkt.email.v1beta1.EmailAddressR\x04from\x12;\n" +
	"\breply_to\x18\x02 \x01(\v2 .dtkt.email.v1beta1.EmailAddressR\areplyTo\x120\n" +
	"\x02to\x18\x03 \x03(\v2 .dtkt.email.v1beta1.EmailAddressR\x02to\x120\n" +
	"\x02cc\x18\x04 \x03(\v2 .dtkt.email.v1beta1.EmailAddressR\x02cc\x122\n" +
	"\x03bcc\x18\x05 \x03(\v2 .dtkt.email.v1beta1.EmailAddressR\x03bcc\x12A\n" +
	"\vreturn_path\x18\x06 \x01(\v2 .dtkt.email.v1beta1.EmailAddressR\n" +
	"returnPath\x12\x18\n" +
	"\asubject\x18\a \x01(\tR\asubject\x12\x1b\n" +
	"\ttext_body\x18\b \x01(\tR\btextBody\x12\x1b\n" +
	"\thtml_body\x18\t \x01(\tR\bhtmlBody\"\xb5\x01\n" +
	"\rEmailTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\blanguage\x18\x02 \x01(\x0e2$.dtkt.email.v1beta1.TemplateLanguageR\blanguage\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x1b\n" +
	"\ttext_body\x18\x04 \x01(\tR\btextBody\x12\x1b\n" +
	"\thtml_body\x18\x05 \x01(\tR\bhtmlBody\"\xa9\x04\n" +
	"\x11EmailWithTemplate\x124\n" +
	"\x04from\x18\x01 \x01(\v2 .dtkt.email.v1beta1.EmailAddressR\x04from\x12;\n" +
	"\breply_to\x18\x02 \x01(\v2 .dtkt.email.v1beta1.EmailAddressR\areplyTo\x120\n" +
	"\x02to\x18\x03 \x03(\v2 .dtkt.email.v1beta1.EmailAddressR\x02to\x120\n" +
	"\x02cc\x18\x04 \x03(\v2 .dtkt.email.v1beta1.EmailAddressR\x02cc\x122\n" +
	"\x03bcc\x18\x05 \x03(\v2 .dtkt.email.v1beta1.EmailAddressR\x03bcc\x12A\n" +
	"\vreturn_path\x18\x06 \x01(\v2 .dtkt.email.v1beta1.EmailAddressR\n" +
	"returnPath\x12\x1f\n" +
	"\vtemplate_id\x18\a \x01(\tR\n" +
	"templateId\x12b\n" +
	"\x0ftemplate_params\x18\b \x03(\v29.dtkt.email.v1beta1.EmailWithTemplate.TemplateParamsEntryR\x0etemplateParams\x1aA\n" +
	"\x13TemplateParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x10SendEmailRequest\x12/\n" +
	"\x05email\x18\x01 \x01(\v2\x19.dtkt.email.v1beta1.EmailR\x05email\"Y\n" +
	"\x11SendEmailResponse\x12D\n" +
	"\vsend_status\x18\x01 \x01(\v2#.dtkt.email.v1beta1.EmailSendStatusR\n" +
	"sendStatus\"D\n" +
	"\x11SendEmailsRequest\x12/\n" +
	"\x05email\x18\x01 \x01(\v2\x19.dtkt.email.v1beta1.EmailR\x05email\"Z\n" +
	"\x12SendEmailsResponse\x12D\n" +
	"\vsend_status\x18\x01 \x01(\v2#.dtkt.email.v1beta1.EmailSendStatusR\n" +
	"sendStatus\"J\n" +
	"\x15SendBatchEmailRequest\x121\n" +
	"\x06emails\x18\x01 \x03(\v2\x19.dtkt.email.v1beta1.EmailR\x06emails\"^\n" +
	"\x16SendBatchEmailResponse\x12D\n" +
	"\vsend_status\x18\x01 \x03(\v2#.dtkt.email.v1beta1.EmailSendStatusR\n" +
	"sendStatus\"[\n" +
	"\x1cSendEmailWithTemplateRequest\x12;\n" +
	"\x05email\x18\x01 \x01(\v2%.dtkt.email.v1beta1.EmailWithTemplateR\x05email\"e\n" +
	"\x1dSendEmailWithTemplateResponse\x12D\n" +
	"\vsend_status\x18\x01 \x01(\v2#.dtkt.email.v1beta1.EmailSendStatusR\n" +
	"sendStatus\"\\\n" +
	"\x1dSendEmailsWithTemplateRequest\x12;\n" +
	"\x05email\x18\x01 \x01(\v2%.dtkt.email.v1beta1.EmailWithTemplateR\x05email\"f\n" +
	"\x1eSendEmailsWithTemplateResponse\x12D\n" +
	"\vsend_status\x18\x01 \x01(\v2#.dtkt.email.v1beta1.EmailSendStatusR\n" +
	"sendStatus\"b\n" +
	"!SendBatchEmailWithTemplateRequest\x12=\n" +
	"\x06emails\x18\x01 \x03(\v2%.dtkt.email.v1beta1.EmailWithTemplateR\x06emails\"j\n" +
	"\"SendBatchEmailWithTemplateResponse\x12D\n" +
	"\vsend_status\x18\x01 \x03(\v2#.dtkt.email.v1beta1.EmailSendStatusR\n" +
	"sendStatus\")\n" +
	"\x17GetEmailTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Y\n" +
	"\x18GetEmailTemplateResponse\x12=\n" +
	"\btemplate\x18\x01 \x01(\v2!.dtkt.email.v1beta1.EmailTemplateR\btemplate\"W\n" +
	"\x19ListEmailTemplatesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x85\x01\n" +
	"\x1aListEmailTemplatesResponse\x12?\n" +
	"\ttemplates\x18\x01 \x03(\v2!.dtkt.email.v1beta1.EmailTemplateR\ttemplates\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"[\n" +
	"\x1aCreateEmailTemplateRequest\x12=\n" +
	"\btemplate\x18\x01 \x01(\v2!.dtkt.email.v1beta1.EmailTemplateR\btemplate\"\\\n" +
	"\x1bCreateEmailTemplateResponse\x12=\n" +
	"\btemplate\x18\x01 \x01(\v2!.dtkt.email.v1beta1.EmailTemplateR\btemplate\"k\n" +
	"\x1aUpdateEmailTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\btemplate\x18\x02 \x01(\v2!.dtkt.email.v1beta1.EmailTemplateR\btemplate\"\\\n" +
	"\x1bUpdateEmailTemplateResponse\x12=\n" +
	"\btemplate\x18\x01 \x01(\v2!.dtkt.email.v1beta1.EmailTemplateR\btemplate\",\n" +
	"\x1aDeleteEmailTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x1bDeleteEmailTemplateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"`\n" +
	"\rReceivedEmail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02at\x18\x02 \x01(\tR\x02at\x12/\n" +
	"\x05email\x18\x03 \x01(\v2\x19.dtkt.email.v1beta1.EmailR\x05email*y\n" +
	"\x10TemplateLanguage\x12!\n" +
	"\x1dTEMPLATE_LANGUAGE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dTEMPLATE_LANGUAGE_GO_TEMPLATE\x10\x01\x12\x1f\n" +
	"\x1bTEMPLATE_LANGUAGE_MUSTACHIO\x10\x02B\xe1\x01\n" +
	"\x18proto.dtkt.email.v1beta1B\rMessagesProtoP\x01ZLgithub.com/datakit-dev/dtkt-sdk/sdk-go/proto/dtkt/email/v1beta1;emailv1beta1\xa2\x02\x03DEX\xaa\x02\x12Dtkt.Email.V1beta1\xca\x02\x12Dtkt\\Email\\V1beta1\xe2\x02\x1eDtkt\\Email\\V1beta1\\GPBMetadata\xea\x02\x14Dtkt::Email::V1beta1b\x06proto3"

var (
	file_dtkt_email_v1beta1_messages_proto_rawDescOnce sync.Once
	file_dtkt_email_v1beta1_messages_proto_rawDescData []byte
)

func file_dtkt_email_v1beta1_messages_proto_rawDescGZIP() []byte {
	file_dtkt_email_v1beta1_messages_proto_rawDescOnce.Do(func() {
		file_dtkt_email_v1beta1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dtkt_email_v1beta1_messages_proto_rawDesc), len(file_dtkt_email_v1beta1_messages_proto_rawDesc)))
	})
	return file_dtkt_email_v1beta1_messages_proto_rawDescData
}

var file_dtkt_email_v1beta1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dtkt_email_v1beta1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_dtkt_email_v1beta1_messages_proto_goTypes = []any{
	(TemplateLanguage)(0),                      // 0: dtkt.email.v1beta1.TemplateLanguage
	(*EmailAddress)(nil),                       // 1: dtkt.email.v1beta1.EmailAddress
	(*EmailSendStatus)(nil),                    // 2: dtkt.email.v1beta1.EmailSendStatus
	(*Email)(nil),                              // 3: dtkt.email.v1beta1.Email
	(*EmailTemplate)(nil),                      // 4: dtkt.email.v1beta1.EmailTemplate
	(*EmailWithTemplate)(nil),                  // 5: dtkt.email.v1beta1.EmailWithTemplate
	(*SendEmailRequest)(nil),                   // 6: dtkt.email.v1beta1.SendEmailRequest
	(*SendEmailResponse)(nil),                  // 7: dtkt.email.v1beta1.SendEmailResponse
	(*SendEmailsRequest)(nil),                  // 8: dtkt.email.v1beta1.SendEmailsRequest
	(*SendEmailsResponse)(nil),                 // 9: dtkt.email.v1beta1.SendEmailsResponse
	(*SendBatchEmailRequest)(nil),              // 10: dtkt.email.v1beta1.SendBatchEmailRequest
	(*SendBatchEmailResponse)(nil),             // 11: dtkt.email.v1beta1.SendBatchEmailResponse
	(*SendEmailWithTemplateRequest)(nil),       // 12: dtkt.email.v1beta1.SendEmailWithTemplateRequest
	(*SendEmailWithTemplateResponse)(nil),      // 13: dtkt.email.v1beta1.SendEmailWithTemplateResponse
	(*SendEmailsWithTemplateRequest)(nil),      // 14: dtkt.email.v1beta1.SendEmailsWithTemplateRequest
	(*SendEmailsWithTemplateResponse)(nil),     // 15: dtkt.email.v1beta1.SendEmailsWithTemplateResponse
	(*SendBatchEmailWithTemplateRequest)(nil),  // 16: dtkt.email.v1beta1.SendBatchEmailWithTemplateRequest
	(*SendBatchEmailWithTemplateResponse)(nil), // 17: dtkt.email.v1beta1.SendBatchEmailWithTemplateResponse
	(*GetEmailTemplateRequest)(nil),            // 18: dtkt.email.v1beta1.GetEmailTemplateRequest
	(*GetEmailTemplateResponse)(nil),           // 19: dtkt.email.v1beta1.GetEmailTemplateResponse
	(*ListEmailTemplatesRequest)(nil),          // 20: dtkt.email.v1beta1.ListEmailTemplatesRequest
	(*ListEmailTemplatesResponse)(nil),         // 21: dtkt.email.v1beta1.ListEmailTemplatesResponse
	(*CreateEmailTemplateRequest)(nil),         // 22: dtkt.email.v1beta1.CreateEmailTemplateRequest
	(*CreateEmailTemplateResponse)(nil),        // 23: dtkt.email.v1beta1.CreateEmailTemplateResponse
	(*UpdateEmailTemplateRequest)(nil),         // 24: dtkt.email.v1beta1.UpdateEmailTemplateRequest
	(*UpdateEmailTemplateResponse)(nil),        // 25: dtkt.email.v1beta1.UpdateEmailTemplateResponse
	(*DeleteEmailTemplateRequest)(nil),         // 26: dtkt.email.v1beta1.DeleteEmailTemplateRequest
	(*DeleteEmailTemplateResponse)(nil),        // 27: dtkt.email.v1beta1.DeleteEmailTemplateResponse
	(*ReceivedEmail)(nil),                      // 28: dtkt.email.v1beta1.ReceivedEmail
	nil,                                        // 29: dtkt.email.v1beta1.EmailWithTemplate.TemplateParamsEntry
}
var file_dtkt_email_v1beta1_messages_proto_depIdxs = []int32{
	1,  // 0: dtkt.email.v1beta1.Email.from:type_name -> dtkt.email.v1beta1.EmailAddress
	1,  // 1: dtkt.email.v1beta1.Email.reply_to:type_name -> dtkt.email.v1beta1.EmailAddress
	1,  // 2: dtkt.email.v1beta1.Email.to:type_name -> dtkt.email.v1beta1.EmailAddress
	1,  // 3: dtkt.email.v1beta1.Email.cc:type_name -> dtkt.email.v1beta1.EmailAddress
	1,  // 4: dtkt.email.v1beta1.Email.bcc:type_name -> dtkt.email.v1beta1.EmailAddress
	1,  // 5: dtkt.email.v1beta1.Email.return_path:type_name -> dtkt.email.v1beta1.EmailAddress
	0,  // 6: dtkt.email.v1beta1.EmailTemplate.language:type_name -> dtkt.email.v1beta1.TemplateLanguage
	1,  // 7: dtkt.email.v1beta1.EmailWithTemplate.from:type_name -> dtkt.email.v1beta1.EmailAddress
	1,  // 8: dtkt.email.v1beta1.EmailWithTemplate.reply_to:type_name -> dtkt.email.v1beta1.EmailAddress
	1,  // 9: dtkt.email.v1beta1.EmailWithTemplate.to:type_name -> dtkt.email.v1beta1.EmailAddress
	1,  // 10: dtkt.email.v1beta1.EmailWithTemplate.cc:type_name -> dtkt.email.v1beta1.EmailAddress
	1,  // 11: dtkt.email.v1beta1.EmailWithTemplate.bcc:type_name -> dtkt.email.v1beta1.EmailAddress
	1,  // 12: dtkt.email.v1beta1.EmailWithTemplate.return_path:type_name -> dtkt.email.v1beta1.EmailAddress
	29, // 13: dtkt.email.v1beta1.EmailWithTemplate.template_params:type_name -> dtkt.email.v1beta1.EmailWithTemplate.TemplateParamsEntry
	3,  // 14: dtkt.email.v1beta1.SendEmailRequest.email:type_name -> dtkt.email.v1beta1.Email
	2,  // 15: dtkt.email.v1beta1.SendEmailResponse.send_status:type_name -> dtkt.email.v1beta1.EmailSendStatus
	3,  // 16: dtkt.email.v1beta1.SendEmailsRequest.email:type_name -> dtkt.email.v1beta1.Email
	2,  // 17: dtkt.email.v1beta1.SendEmailsResponse.send_status:type_name -> dtkt.email.v1beta1.EmailSendStatus
	3,  // 18: dtkt.email.v1beta1.SendBatchEmailRequest.emails:type_name -> dtkt.email.v1beta1.Email
	2,  // 19: dtkt.email.v1beta1.SendBatchEmailResponse.send_status:type_name -> dtkt.email.v1beta1.EmailSendStatus
	5,  // 20: dtkt.email.v1beta1.SendEmailWithTemplateRequest.email:type_name -> dtkt.email.v1beta1.EmailWithTemplate
	2,  // 21: dtkt.email.v1beta1.SendEmailWithTemplateResponse.send_status:type_name -> dtkt.email.v1beta1.EmailSendStatus
	5,  // 22: dtkt.email.v1beta1.SendEmailsWithTemplateRequest.email:type_name -> dtkt.email.v1beta1.EmailWithTemplate
	2,  // 23: dtkt.email.v1beta1.SendEmailsWithTemplateResponse.send_status:type_name -> dtkt.email.v1beta1.EmailSendStatus
	5,  // 24: dtkt.email.v1beta1.SendBatchEmailWithTemplateRequest.emails:type_name -> dtkt.email.v1beta1.EmailWithTemplate
	2,  // 25: dtkt.email.v1beta1.SendBatchEmailWithTemplateResponse.send_status:type_name -> dtkt.email.v1beta1.EmailSendStatus
	4,  // 26: dtkt.email.v1beta1.GetEmailTemplateResponse.template:type_name -> dtkt.email.v1beta1.EmailTemplate
	4,  // 27: dtkt.email.v1beta1.ListEmailTemplatesResponse.templates:type_name -> dtkt.email.v1beta1.EmailTemplate
	4,  // 28: dtkt.email.v1beta1.CreateEmailTemplateRequest.template:type_name -> dtkt.email.v1beta1.EmailTemplate
	4,  // 29: dtkt.email.v1beta1.CreateEmailTemplateResponse.template:type_name -> dtkt.email.v1beta1.EmailTemplate
	4,  // 30: dtkt.email.v1beta1.UpdateEmailTemplateRequest.template:type_name -> dtkt.email.v1beta1.EmailTemplate
	4,  // 31: dtkt.email.v1beta1.UpdateEmailTemplateResponse.template:type_name -> dtkt.email.v1beta1.EmailTemplate
	3,  // 32: dtkt.email.v1beta1.ReceivedEmail.email:type_name -> dtkt.email.v1beta1.Email
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_dtkt_email_v1beta1_messages_proto_init() }
func file_dtkt_email_v1beta1_messages_proto_init() {
	if File_dtkt_email_v1beta1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dtkt_email_v1beta1_messages_proto_rawDesc), len(file_dtkt_email_v1beta1_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dtkt_email_v1beta1_messages_proto_goTypes,
		DependencyIndexes: file_dtkt_email_v1beta1_messages_proto_depIdxs,
		EnumInfos:         file_dtkt_email_v1beta1_messages_proto_enumTypes,
		MessageInfos:      file_dtkt_email_v1beta1_messages_proto_msgTypes,
	}.Build()
	File_dtkt_email_v1beta1_messages_proto = out.File
	file_dtkt_email_v1beta1_messages_proto_goTypes = nil
	file_dtkt_email_v1beta1_messages_proto_depIdxs = nil
}
