// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: dtkt/email/v1beta1/services.proto

package emailv1beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmailService_SendEmail_FullMethodName                  = "/dtkt.email.v1beta1.EmailService/SendEmail"
	EmailService_SendEmails_FullMethodName                 = "/dtkt.email.v1beta1.EmailService/SendEmails"
	EmailService_SendBatchEmail_FullMethodName             = "/dtkt.email.v1beta1.EmailService/SendBatchEmail"
	EmailService_SendEmailWithTemplate_FullMethodName      = "/dtkt.email.v1beta1.EmailService/SendEmailWithTemplate"
	EmailService_SendEmailsWithTemplate_FullMethodName     = "/dtkt.email.v1beta1.EmailService/SendEmailsWithTemplate"
	EmailService_SendBatchEmailWithTemplate_FullMethodName = "/dtkt.email.v1beta1.EmailService/SendBatchEmailWithTemplate"
	EmailService_ListEmailTemplates_FullMethodName         = "/dtkt.email.v1beta1.EmailService/ListEmailTemplates"
	EmailService_GetEmailTemplate_FullMethodName           = "/dtkt.email.v1beta1.EmailService/GetEmailTemplate"
	EmailService_CreateEmailTemplate_FullMethodName        = "/dtkt.email.v1beta1.EmailService/CreateEmailTemplate"
	EmailService_UpdateEmailTemplate_FullMethodName        = "/dtkt.email.v1beta1.EmailService/UpdateEmailTemplate"
	EmailService_DeleteEmailTemplate_FullMethodName        = "/dtkt.email.v1beta1.EmailService/DeleteEmailTemplate"
)

// EmailServiceClient is the client API for EmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EmailService provides operations for sending emails.
type EmailServiceClient interface {
	// Sends an email message.
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
	// Sends a stream of email messages.
	SendEmails(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SendEmailsRequest, SendEmailsResponse], error)
	// Sends a batch of email messages.
	SendBatchEmail(ctx context.Context, in *SendBatchEmailRequest, opts ...grpc.CallOption) (*SendBatchEmailResponse, error)
	// Sends an email message with a template.
	SendEmailWithTemplate(ctx context.Context, in *SendEmailWithTemplateRequest, opts ...grpc.CallOption) (*SendEmailWithTemplateResponse, error)
	// Sends a stream of email messages with a template.
	SendEmailsWithTemplate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SendEmailsWithTemplateRequest, SendEmailsWithTemplateResponse], error)
	// Sends a batch of email messages with a template.
	SendBatchEmailWithTemplate(ctx context.Context, in *SendBatchEmailWithTemplateRequest, opts ...grpc.CallOption) (*SendBatchEmailWithTemplateResponse, error)
	// Get the list of email templates.
	ListEmailTemplates(ctx context.Context, in *ListEmailTemplatesRequest, opts ...grpc.CallOption) (*ListEmailTemplatesResponse, error)
	// Get an email template by ID.
	GetEmailTemplate(ctx context.Context, in *GetEmailTemplateRequest, opts ...grpc.CallOption) (*GetEmailTemplateResponse, error)
	// Creates an email template.
	CreateEmailTemplate(ctx context.Context, in *CreateEmailTemplateRequest, opts ...grpc.CallOption) (*CreateEmailTemplateResponse, error)
	// Updates an email template.
	UpdateEmailTemplate(ctx context.Context, in *UpdateEmailTemplateRequest, opts ...grpc.CallOption) (*UpdateEmailTemplateResponse, error)
	// Deletes an email template.
	DeleteEmailTemplate(ctx context.Context, in *DeleteEmailTemplateRequest, opts ...grpc.CallOption) (*DeleteEmailTemplateResponse, error)
}

type emailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailServiceClient(cc grpc.ClientConnInterface) EmailServiceClient {
	return &emailServiceClient{cc}
}

func (c *emailServiceClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, EmailService_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) SendEmails(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SendEmailsRequest, SendEmailsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmailService_ServiceDesc.Streams[0], EmailService_SendEmails_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendEmailsRequest, SendEmailsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmailService_SendEmailsClient = grpc.BidiStreamingClient[SendEmailsRequest, SendEmailsResponse]

func (c *emailServiceClient) SendBatchEmail(ctx context.Context, in *SendBatchEmailRequest, opts ...grpc.CallOption) (*SendBatchEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendBatchEmailResponse)
	err := c.cc.Invoke(ctx, EmailService_SendBatchEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) SendEmailWithTemplate(ctx context.Context, in *SendEmailWithTemplateRequest, opts ...grpc.CallOption) (*SendEmailWithTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailWithTemplateResponse)
	err := c.cc.Invoke(ctx, EmailService_SendEmailWithTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) SendEmailsWithTemplate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SendEmailsWithTemplateRequest, SendEmailsWithTemplateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmailService_ServiceDesc.Streams[1], EmailService_SendEmailsWithTemplate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendEmailsWithTemplateRequest, SendEmailsWithTemplateResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmailService_SendEmailsWithTemplateClient = grpc.BidiStreamingClient[SendEmailsWithTemplateRequest, SendEmailsWithTemplateResponse]

func (c *emailServiceClient) SendBatchEmailWithTemplate(ctx context.Context, in *SendBatchEmailWithTemplateRequest, opts ...grpc.CallOption) (*SendBatchEmailWithTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendBatchEmailWithTemplateResponse)
	err := c.cc.Invoke(ctx, EmailService_SendBatchEmailWithTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) ListEmailTemplates(ctx context.Context, in *ListEmailTemplatesRequest, opts ...grpc.CallOption) (*ListEmailTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEmailTemplatesResponse)
	err := c.cc.Invoke(ctx, EmailService_ListEmailTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) GetEmailTemplate(ctx context.Context, in *GetEmailTemplateRequest, opts ...grpc.CallOption) (*GetEmailTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmailTemplateResponse)
	err := c.cc.Invoke(ctx, EmailService_GetEmailTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) CreateEmailTemplate(ctx context.Context, in *CreateEmailTemplateRequest, opts ...grpc.CallOption) (*CreateEmailTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEmailTemplateResponse)
	err := c.cc.Invoke(ctx, EmailService_CreateEmailTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) UpdateEmailTemplate(ctx context.Context, in *UpdateEmailTemplateRequest, opts ...grpc.CallOption) (*UpdateEmailTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEmailTemplateResponse)
	err := c.cc.Invoke(ctx, EmailService_UpdateEmailTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) DeleteEmailTemplate(ctx context.Context, in *DeleteEmailTemplateRequest, opts ...grpc.CallOption) (*DeleteEmailTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEmailTemplateResponse)
	err := c.cc.Invoke(ctx, EmailService_DeleteEmailTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServiceServer is the server API for EmailService service.
// All implementations must embed UnimplementedEmailServiceServer
// for forward compatibility.
//
// EmailService provides operations for sending emails.
type EmailServiceServer interface {
	// Sends an email message.
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
	// Sends a stream of email messages.
	SendEmails(grpc.BidiStreamingServer[SendEmailsRequest, SendEmailsResponse]) error
	// Sends a batch of email messages.
	SendBatchEmail(context.Context, *SendBatchEmailRequest) (*SendBatchEmailResponse, error)
	// Sends an email message with a template.
	SendEmailWithTemplate(context.Context, *SendEmailWithTemplateRequest) (*SendEmailWithTemplateResponse, error)
	// Sends a stream of email messages with a template.
	SendEmailsWithTemplate(grpc.BidiStreamingServer[SendEmailsWithTemplateRequest, SendEmailsWithTemplateResponse]) error
	// Sends a batch of email messages with a template.
	SendBatchEmailWithTemplate(context.Context, *SendBatchEmailWithTemplateRequest) (*SendBatchEmailWithTemplateResponse, error)
	// Get the list of email templates.
	ListEmailTemplates(context.Context, *ListEmailTemplatesRequest) (*ListEmailTemplatesResponse, error)
	// Get an email template by ID.
	GetEmailTemplate(context.Context, *GetEmailTemplateRequest) (*GetEmailTemplateResponse, error)
	// Creates an email template.
	CreateEmailTemplate(context.Context, *CreateEmailTemplateRequest) (*CreateEmailTemplateResponse, error)
	// Updates an email template.
	UpdateEmailTemplate(context.Context, *UpdateEmailTemplateRequest) (*UpdateEmailTemplateResponse, error)
	// Deletes an email template.
	DeleteEmailTemplate(context.Context, *DeleteEmailTemplateRequest) (*DeleteEmailTemplateResponse, error)
	mustEmbedUnimplementedEmailServiceServer()
}

// UnimplementedEmailServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmailServiceServer struct{}

func (UnimplementedEmailServiceServer) SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedEmailServiceServer) SendEmails(grpc.BidiStreamingServer[SendEmailsRequest, SendEmailsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SendEmails not implemented")
}
func (UnimplementedEmailServiceServer) SendBatchEmail(context.Context, *SendBatchEmailRequest) (*SendBatchEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBatchEmail not implemented")
}
func (UnimplementedEmailServiceServer) SendEmailWithTemplate(context.Context, *SendEmailWithTemplateRequest) (*SendEmailWithTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailWithTemplate not implemented")
}
func (UnimplementedEmailServiceServer) SendEmailsWithTemplate(grpc.BidiStreamingServer[SendEmailsWithTemplateRequest, SendEmailsWithTemplateResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SendEmailsWithTemplate not implemented")
}
func (UnimplementedEmailServiceServer) SendBatchEmailWithTemplate(context.Context, *SendBatchEmailWithTemplateRequest) (*SendBatchEmailWithTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBatchEmailWithTemplate not implemented")
}
func (UnimplementedEmailServiceServer) ListEmailTemplates(context.Context, *ListEmailTemplatesRequest) (*ListEmailTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEmailTemplates not implemented")
}
func (UnimplementedEmailServiceServer) GetEmailTemplate(context.Context, *GetEmailTemplateRequest) (*GetEmailTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmailTemplate not implemented")
}
func (UnimplementedEmailServiceServer) CreateEmailTemplate(context.Context, *CreateEmailTemplateRequest) (*CreateEmailTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEmailTemplate not implemented")
}
func (UnimplementedEmailServiceServer) UpdateEmailTemplate(context.Context, *UpdateEmailTemplateRequest) (*UpdateEmailTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEmailTemplate not implemented")
}
func (UnimplementedEmailServiceServer) DeleteEmailTemplate(context.Context, *DeleteEmailTemplateRequest) (*DeleteEmailTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEmailTemplate not implemented")
}
func (UnimplementedEmailServiceServer) mustEmbedUnimplementedEmailServiceServer() {}
func (UnimplementedEmailServiceServer) testEmbeddedByValue()                      {}

// UnsafeEmailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailServiceServer will
// result in compilation errors.
type UnsafeEmailServiceServer interface {
	mustEmbedUnimplementedEmailServiceServer()
}

func RegisterEmailServiceServer(s grpc.ServiceRegistrar, srv EmailServiceServer) {
	// If the following call pancis, it indicates UnimplementedEmailServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmailService_ServiceDesc, srv)
}

func _EmailService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_SendEmails_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmailServiceServer).SendEmails(&grpc.GenericServerStream[SendEmailsRequest, SendEmailsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmailService_SendEmailsServer = grpc.BidiStreamingServer[SendEmailsRequest, SendEmailsResponse]

func _EmailService_SendBatchEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBatchEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendBatchEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_SendBatchEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendBatchEmail(ctx, req.(*SendBatchEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_SendEmailWithTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailWithTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendEmailWithTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_SendEmailWithTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendEmailWithTemplate(ctx, req.(*SendEmailWithTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_SendEmailsWithTemplate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmailServiceServer).SendEmailsWithTemplate(&grpc.GenericServerStream[SendEmailsWithTemplateRequest, SendEmailsWithTemplateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmailService_SendEmailsWithTemplateServer = grpc.BidiStreamingServer[SendEmailsWithTemplateRequest, SendEmailsWithTemplateResponse]

func _EmailService_SendBatchEmailWithTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBatchEmailWithTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendBatchEmailWithTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_SendBatchEmailWithTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendBatchEmailWithTemplate(ctx, req.(*SendBatchEmailWithTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_ListEmailTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEmailTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).ListEmailTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_ListEmailTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).ListEmailTemplates(ctx, req.(*ListEmailTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_GetEmailTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmailTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).GetEmailTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_GetEmailTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).GetEmailTemplate(ctx, req.(*GetEmailTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_CreateEmailTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEmailTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).CreateEmailTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_CreateEmailTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).CreateEmailTemplate(ctx, req.(*CreateEmailTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_UpdateEmailTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmailTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).UpdateEmailTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_UpdateEmailTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).UpdateEmailTemplate(ctx, req.(*UpdateEmailTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_DeleteEmailTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEmailTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).DeleteEmailTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_DeleteEmailTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).DeleteEmailTemplate(ctx, req.(*DeleteEmailTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailService_ServiceDesc is the grpc.ServiceDesc for EmailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dtkt.email.v1beta1.EmailService",
	HandlerType: (*EmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _EmailService_SendEmail_Handler,
		},
		{
			MethodName: "SendBatchEmail",
			Handler:    _EmailService_SendBatchEmail_Handler,
		},
		{
			MethodName: "SendEmailWithTemplate",
			Handler:    _EmailService_SendEmailWithTemplate_Handler,
		},
		{
			MethodName: "SendBatchEmailWithTemplate",
			Handler:    _EmailService_SendBatchEmailWithTemplate_Handler,
		},
		{
			MethodName: "ListEmailTemplates",
			Handler:    _EmailService_ListEmailTemplates_Handler,
		},
		{
			MethodName: "GetEmailTemplate",
			Handler:    _EmailService_GetEmailTemplate_Handler,
		},
		{
			MethodName: "CreateEmailTemplate",
			Handler:    _EmailService_CreateEmailTemplate_Handler,
		},
		{
			MethodName: "UpdateEmailTemplate",
			Handler:    _EmailService_UpdateEmailTemplate_Handler,
		},
		{
			MethodName: "DeleteEmailTemplate",
			Handler:    _EmailService_DeleteEmailTemplate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendEmails",
			Handler:       _EmailService_SendEmails_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendEmailsWithTemplate",
			Handler:       _EmailService_SendEmailsWithTemplate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dtkt/email/v1beta1/services.proto",
}
