// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: dtkt/event/v1beta1/messages.proto

//go:build !protoopaque

package eventv1beta1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/datakit-dev/dtkt-sdk/sdk-go/proto/dtkt/protoform/v1beta1"
	v1beta1 "github.com/datakit-dev/dtkt-sdk/sdk-go/proto/dtkt/shared/v1beta1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventSource_State int32

const (
	// Unspecified state.
	EventSource_STATE_UNSPECIFIED EventSource_State = 0
	// Event source is properly configured and active.
	EventSource_STATE_ACTIVE EventSource_State = 1
	// Event source is not properly configured and inactive.
	EventSource_STATE_INACTIVE EventSource_State = 2
)

// Enum value maps for EventSource_State.
var (
	EventSource_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_ACTIVE",
		2: "STATE_INACTIVE",
	}
	EventSource_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_ACTIVE":      1,
		"STATE_INACTIVE":    2,
	}
)

func (x EventSource_State) Enum() *EventSource_State {
	p := new(EventSource_State)
	*p = x
	return p
}

func (x EventSource_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventSource_State) Descriptor() protoreflect.EnumDescriptor {
	return file_dtkt_event_v1beta1_messages_proto_enumTypes[0].Descriptor()
}

func (EventSource_State) Type() protoreflect.EnumType {
	return &file_dtkt_event_v1beta1_messages_proto_enumTypes[0]
}

func (x EventSource_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Represents an event deliverable by an event source with its associated
// metadata including a schema of the event payload.
type Event struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier for this event, e.g. `events/new-email-received`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The name shown to users in the UI, e.g. "New Email Received".
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// A short explanation of the event, shown to users when selecting or reviewing it.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Schema describing the payload of the event.
	PayloadSchema *v1beta1.TypeSchema `protobuf:"bytes,4,opt,name=payload_schema,json=payloadSchema,proto3" json:"payload_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetPayloadSchema() *v1beta1.TypeSchema {
	if x != nil {
		return x.PayloadSchema
	}
	return nil
}

func (x *Event) SetName(v string) {
	x.Name = v
}

func (x *Event) SetDisplayName(v string) {
	x.DisplayName = v
}

func (x *Event) SetDescription(v string) {
	x.Description = v
}

func (x *Event) SetPayloadSchema(v *v1beta1.TypeSchema) {
	x.PayloadSchema = v
}

func (x *Event) HasPayloadSchema() bool {
	if x == nil {
		return false
	}
	return x.PayloadSchema != nil
}

func (x *Event) ClearPayloadSchema() {
	x.PayloadSchema = nil
}

type Event_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier for this event, e.g. `events/new-email-received`.
	Name string
	// The name shown to users in the UI, e.g. "New Email Received".
	DisplayName string
	// A short explanation of the event, shown to users when selecting or reviewing it.
	Description string
	// Schema describing the payload of the event.
	PayloadSchema *v1beta1.TypeSchema
}

func (b0 Event_builder) Build() *Event {
	m0 := &Event{}
	b, x := &b0, m0
	_, _ = b, x
	x.Name = b.Name
	x.DisplayName = b.DisplayName
	x.Description = b.Description
	x.PayloadSchema = b.PayloadSchema
	return m0
}

// Represents an event source supported by the service.
type EventSource struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier for this event source, e.g. `event_sources/new-email-received-source`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The name shown to users in the UI, e.g. "New Email Received".
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// A short explanation of the event, shown to users when selecting or reviewing it.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Schema for configuring the event source.
	ConfigSchema *v1beta1.TypeSchema `protobuf:"bytes,4,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	// Specifies if configuration is required before using the event source.
	RequiresConfig bool `protobuf:"varint,5,opt,name=requires_config,json=requiresConfig,proto3" json:"requires_config,omitempty"`
	// Specifies if the event source should continue delivering events even if
	// errors are encountered.
	ContinueOnError bool `protobuf:"varint,6,opt,name=continue_on_error,json=continueOnError,proto3" json:"continue_on_error,omitempty"`
	// Configuration of the event source.
	Config *anypb.Any `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`
	// Current state of the event source.
	State EventSource_State `protobuf:"varint,8,opt,name=state,proto3,enum=dtkt.event.v1beta1.EventSource_State" json:"state,omitempty"`
	// Types that are valid to be assigned to Strategy:
	//
	//	*EventSource_PullFreq
	//	*EventSource_PushUrl
	Strategy      isEventSource_Strategy `protobuf_oneof:"strategy"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSource) Reset() {
	*x = EventSource{}
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSource) ProtoMessage() {}

func (x *EventSource) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventSource) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *EventSource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventSource) GetConfigSchema() *v1beta1.TypeSchema {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

func (x *EventSource) GetRequiresConfig() bool {
	if x != nil {
		return x.RequiresConfig
	}
	return false
}

func (x *EventSource) GetContinueOnError() bool {
	if x != nil {
		return x.ContinueOnError
	}
	return false
}

func (x *EventSource) GetConfig() *anypb.Any {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *EventSource) GetState() EventSource_State {
	if x != nil {
		return x.State
	}
	return EventSource_STATE_UNSPECIFIED
}

func (x *EventSource) GetStrategy() isEventSource_Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *EventSource) GetPullFreq() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Strategy.(*EventSource_PullFreq); ok {
			return x.PullFreq
		}
	}
	return nil
}

func (x *EventSource) GetPushUrl() string {
	if x != nil {
		if x, ok := x.Strategy.(*EventSource_PushUrl); ok {
			return x.PushUrl
		}
	}
	return ""
}

func (x *EventSource) SetName(v string) {
	x.Name = v
}

func (x *EventSource) SetDisplayName(v string) {
	x.DisplayName = v
}

func (x *EventSource) SetDescription(v string) {
	x.Description = v
}

func (x *EventSource) SetConfigSchema(v *v1beta1.TypeSchema) {
	x.ConfigSchema = v
}

func (x *EventSource) SetRequiresConfig(v bool) {
	x.RequiresConfig = v
}

func (x *EventSource) SetContinueOnError(v bool) {
	x.ContinueOnError = v
}

func (x *EventSource) SetConfig(v *anypb.Any) {
	x.Config = v
}

func (x *EventSource) SetState(v EventSource_State) {
	x.State = v
}

func (x *EventSource) SetPullFreq(v *durationpb.Duration) {
	if v == nil {
		x.Strategy = nil
		return
	}
	x.Strategy = &EventSource_PullFreq{v}
}

func (x *EventSource) SetPushUrl(v string) {
	x.Strategy = &EventSource_PushUrl{v}
}

func (x *EventSource) HasConfigSchema() bool {
	if x == nil {
		return false
	}
	return x.ConfigSchema != nil
}

func (x *EventSource) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.Config != nil
}

func (x *EventSource) HasStrategy() bool {
	if x == nil {
		return false
	}
	return x.Strategy != nil
}

func (x *EventSource) HasPullFreq() bool {
	if x == nil {
		return false
	}
	_, ok := x.Strategy.(*EventSource_PullFreq)
	return ok
}

func (x *EventSource) HasPushUrl() bool {
	if x == nil {
		return false
	}
	_, ok := x.Strategy.(*EventSource_PushUrl)
	return ok
}

func (x *EventSource) ClearConfigSchema() {
	x.ConfigSchema = nil
}

func (x *EventSource) ClearConfig() {
	x.Config = nil
}

func (x *EventSource) ClearStrategy() {
	x.Strategy = nil
}

func (x *EventSource) ClearPullFreq() {
	if _, ok := x.Strategy.(*EventSource_PullFreq); ok {
		x.Strategy = nil
	}
}

func (x *EventSource) ClearPushUrl() {
	if _, ok := x.Strategy.(*EventSource_PushUrl); ok {
		x.Strategy = nil
	}
}

const EventSource_Strategy_not_set_case case_EventSource_Strategy = 0
const EventSource_PullFreq_case case_EventSource_Strategy = 9
const EventSource_PushUrl_case case_EventSource_Strategy = 10

func (x *EventSource) WhichStrategy() case_EventSource_Strategy {
	if x == nil {
		return EventSource_Strategy_not_set_case
	}
	switch x.Strategy.(type) {
	case *EventSource_PullFreq:
		return EventSource_PullFreq_case
	case *EventSource_PushUrl:
		return EventSource_PushUrl_case
	default:
		return EventSource_Strategy_not_set_case
	}
}

type EventSource_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier for this event source, e.g. `event_sources/new-email-received-source`.
	Name string
	// The name shown to users in the UI, e.g. "New Email Received".
	DisplayName string
	// A short explanation of the event, shown to users when selecting or reviewing it.
	Description string
	// Schema for configuring the event source.
	ConfigSchema *v1beta1.TypeSchema
	// Specifies if configuration is required before using the event source.
	RequiresConfig bool
	// Specifies if the event source should continue delivering events even if
	// errors are encountered.
	ContinueOnError bool
	// Configuration of the event source.
	Config *anypb.Any
	// Current state of the event source.
	State EventSource_State
	// Fields of oneof Strategy:
	// Pull frequency of the event source.
	PullFreq *durationpb.Duration
	// Push URL of the event source.
	PushUrl *string
	// -- end of Strategy
}

func (b0 EventSource_builder) Build() *EventSource {
	m0 := &EventSource{}
	b, x := &b0, m0
	_, _ = b, x
	x.Name = b.Name
	x.DisplayName = b.DisplayName
	x.Description = b.Description
	x.ConfigSchema = b.ConfigSchema
	x.RequiresConfig = b.RequiresConfig
	x.ContinueOnError = b.ContinueOnError
	x.Config = b.Config
	x.State = b.State
	if b.PullFreq != nil {
		x.Strategy = &EventSource_PullFreq{b.PullFreq}
	}
	if b.PushUrl != nil {
		x.Strategy = &EventSource_PushUrl{*b.PushUrl}
	}
	return m0
}

type case_EventSource_Strategy protoreflect.FieldNumber

func (x case_EventSource_Strategy) String() string {
	md := file_dtkt_event_v1beta1_messages_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isEventSource_Strategy interface {
	isEventSource_Strategy()
}

type EventSource_PullFreq struct {
	// Pull frequency of the event source.
	PullFreq *durationpb.Duration `protobuf:"bytes,9,opt,name=pull_freq,json=pullFreq,proto3,oneof"`
}

type EventSource_PushUrl struct {
	// Push URL of the event source.
	PushUrl string `protobuf:"bytes,10,opt,name=push_url,json=pushUrl,proto3,oneof"`
}

func (*EventSource_PullFreq) isEventSource_Strategy() {}

func (*EventSource_PushUrl) isEventSource_Strategy() {}

// Request for retrieving events.
type ListEventsRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Number of events to return per page. Leave empty for the server default.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Token from a previous response's `next_page_token` to retrieve the next page of results.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional filter expression to narrow results..
	Filter        string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListEventsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListEventsRequest) SetPageSize(v int32) {
	x.PageSize = v
}

func (x *ListEventsRequest) SetPageToken(v string) {
	x.PageToken = v
}

func (x *ListEventsRequest) SetFilter(v string) {
	x.Filter = v
}

type ListEventsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Number of events to return per page. Leave empty for the server default.
	PageSize int32
	// Token from a previous response's `next_page_token` to retrieve the next page of results.
	PageToken string
	// Optional filter expression to narrow results..
	Filter string
}

func (b0 ListEventsRequest_builder) Build() *ListEventsRequest {
	m0 := &ListEventsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.PageSize = b.PageSize
	x.PageToken = b.PageToken
	x.Filter = b.Filter
	return m0
}

// Response containing a list of events.
type ListEventsResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// List of events.
	Events []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// Pass this value as `page_token` in your next request to retrieve the following page. Empty when there are no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListEventsResponse) SetEvents(v []*Event) {
	x.Events = v
}

func (x *ListEventsResponse) SetNextPageToken(v string) {
	x.NextPageToken = v
}

type ListEventsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// List of events.
	Events []*Event
	// Pass this value as `page_token` in your next request to retrieve the following page. Empty when there are no more results.
	NextPageToken string
}

func (b0 ListEventsResponse_builder) Build() *ListEventsResponse {
	m0 := &ListEventsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Events = b.Events
	x.NextPageToken = b.NextPageToken
	return m0
}

// Request for retrieving event source types supported by this service.
type ListEventSourcesRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Number of event sources to return per page. Leave empty for the server default.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Token from a previous response's `next_page_token` to retrieve the next page of results.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional filter expression to narrow results..
	Filter        string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventSourcesRequest) Reset() {
	*x = ListEventSourcesRequest{}
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventSourcesRequest) ProtoMessage() {}

func (x *ListEventSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListEventSourcesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEventSourcesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListEventSourcesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListEventSourcesRequest) SetPageSize(v int32) {
	x.PageSize = v
}

func (x *ListEventSourcesRequest) SetPageToken(v string) {
	x.PageToken = v
}

func (x *ListEventSourcesRequest) SetFilter(v string) {
	x.Filter = v
}

type ListEventSourcesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Number of event sources to return per page. Leave empty for the server default.
	PageSize int32
	// Token from a previous response's `next_page_token` to retrieve the next page of results.
	PageToken string
	// Optional filter expression to narrow results..
	Filter string
}

func (b0 ListEventSourcesRequest_builder) Build() *ListEventSourcesRequest {
	m0 := &ListEventSourcesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.PageSize = b.PageSize
	x.PageToken = b.PageToken
	x.Filter = b.Filter
	return m0
}

// List of event sources supported by or configured for this service.
type ListEventSourcesResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// List of event sources.
	EventSources []*EventSource `protobuf:"bytes,1,rep,name=event_sources,json=eventSources,proto3" json:"event_sources,omitempty"`
	// Pass this value as `page_token` in your next request to retrieve the following page. Empty when there are no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventSourcesResponse) Reset() {
	*x = ListEventSourcesResponse{}
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventSourcesResponse) ProtoMessage() {}

func (x *ListEventSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListEventSourcesResponse) GetEventSources() []*EventSource {
	if x != nil {
		return x.EventSources
	}
	return nil
}

func (x *ListEventSourcesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListEventSourcesResponse) SetEventSources(v []*EventSource) {
	x.EventSources = v
}

func (x *ListEventSourcesResponse) SetNextPageToken(v string) {
	x.NextPageToken = v
}

type ListEventSourcesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// List of event sources.
	EventSources []*EventSource
	// Pass this value as `page_token` in your next request to retrieve the following page. Empty when there are no more results.
	NextPageToken string
}

func (b0 ListEventSourcesResponse_builder) Build() *ListEventSourcesResponse {
	m0 := &ListEventSourcesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.EventSources = b.EventSources
	x.NextPageToken = b.NextPageToken
	return m0
}

// Request to pull events from a PULL event source.
type StreamPullEventsRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Name of pull event source.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Configuration of the event source.
	Config *anypb.Any `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// Pull frequency of the event source.
	PullFreq      *durationpb.Duration `protobuf:"bytes,3,opt,name=pull_freq,json=pullFreq,proto3" json:"pull_freq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPullEventsRequest) Reset() {
	*x = StreamPullEventsRequest{}
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPullEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPullEventsRequest) ProtoMessage() {}

func (x *StreamPullEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamPullEventsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamPullEventsRequest) GetConfig() *anypb.Any {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *StreamPullEventsRequest) GetPullFreq() *durationpb.Duration {
	if x != nil {
		return x.PullFreq
	}
	return nil
}

func (x *StreamPullEventsRequest) SetName(v string) {
	x.Name = v
}

func (x *StreamPullEventsRequest) SetConfig(v *anypb.Any) {
	x.Config = v
}

func (x *StreamPullEventsRequest) SetPullFreq(v *durationpb.Duration) {
	x.PullFreq = v
}

func (x *StreamPullEventsRequest) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.Config != nil
}

func (x *StreamPullEventsRequest) HasPullFreq() bool {
	if x == nil {
		return false
	}
	return x.PullFreq != nil
}

func (x *StreamPullEventsRequest) ClearConfig() {
	x.Config = nil
}

func (x *StreamPullEventsRequest) ClearPullFreq() {
	x.PullFreq = nil
}

type StreamPullEventsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of pull event source.
	Name string
	// Configuration of the event source.
	Config *anypb.Any
	// Pull frequency of the event source.
	PullFreq *durationpb.Duration
}

func (b0 StreamPullEventsRequest_builder) Build() *StreamPullEventsRequest {
	m0 := &StreamPullEventsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Name = b.Name
	x.Config = b.Config
	x.PullFreq = b.PullFreq
	return m0
}

// Response from pulling events.
type StreamPullEventsResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Name of pull event source from request.
	EventSource string `protobuf:"bytes,1,opt,name=event_source,json=eventSource,proto3" json:"event_source,omitempty"`
	// Name of event delivered by event source.
	Event string `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// Payload of the event.
	Payload *anypb.Any `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Type of action associated with event.
	Action        *v1beta1.ActionType `protobuf:"varint,4,opt,name=action,proto3,enum=dtkt.shared.v1beta1.ActionType,oneof" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPullEventsResponse) Reset() {
	*x = StreamPullEventsResponse{}
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPullEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPullEventsResponse) ProtoMessage() {}

func (x *StreamPullEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamPullEventsResponse) GetEventSource() string {
	if x != nil {
		return x.EventSource
	}
	return ""
}

func (x *StreamPullEventsResponse) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *StreamPullEventsResponse) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamPullEventsResponse) GetAction() v1beta1.ActionType {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return v1beta1.ActionType(0)
}

func (x *StreamPullEventsResponse) SetEventSource(v string) {
	x.EventSource = v
}

func (x *StreamPullEventsResponse) SetEvent(v string) {
	x.Event = v
}

func (x *StreamPullEventsResponse) SetPayload(v *anypb.Any) {
	x.Payload = v
}

func (x *StreamPullEventsResponse) SetAction(v v1beta1.ActionType) {
	x.Action = &v
}

func (x *StreamPullEventsResponse) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.Payload != nil
}

func (x *StreamPullEventsResponse) HasAction() bool {
	if x == nil {
		return false
	}
	return x.Action != nil
}

func (x *StreamPullEventsResponse) ClearPayload() {
	x.Payload = nil
}

func (x *StreamPullEventsResponse) ClearAction() {
	x.Action = nil
}

type StreamPullEventsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of pull event source from request.
	EventSource string
	// Name of event delivered by event source.
	Event string
	// Payload of the event.
	Payload *anypb.Any
	// Type of action associated with event.
	Action *v1beta1.ActionType
}

func (b0 StreamPullEventsResponse_builder) Build() *StreamPullEventsResponse {
	m0 := &StreamPullEventsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.EventSource = b.EventSource
	x.Event = b.Event
	x.Payload = b.Payload
	x.Action = b.Action
	return m0
}

// Request to validate an event from a push event source.
type StreamPushEventsRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Name of push event source.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Headers of the event (if any).
	Headers map[string]*v1beta1.StringList `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Body of the event.
	Body          []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPushEventsRequest) Reset() {
	*x = StreamPushEventsRequest{}
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPushEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPushEventsRequest) ProtoMessage() {}

func (x *StreamPushEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamPushEventsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamPushEventsRequest) GetHeaders() map[string]*v1beta1.StringList {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *StreamPushEventsRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *StreamPushEventsRequest) SetName(v string) {
	x.Name = v
}

func (x *StreamPushEventsRequest) SetHeaders(v map[string]*v1beta1.StringList) {
	x.Headers = v
}

func (x *StreamPushEventsRequest) SetBody(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.Body = v
}

type StreamPushEventsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of push event source.
	Name string
	// Headers of the event (if any).
	Headers map[string]*v1beta1.StringList
	// Body of the event.
	Body []byte
}

func (b0 StreamPushEventsRequest_builder) Build() *StreamPushEventsRequest {
	m0 := &StreamPushEventsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Name = b.Name
	x.Headers = b.Headers
	x.Body = b.Body
	return m0
}

// Response of a valid event from a push event source.
type StreamPushEventsResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Name of push event source from request.
	EventSource string `protobuf:"bytes,1,opt,name=event_source,json=eventSource,proto3" json:"event_source,omitempty"`
	// Name of event delivered by event source.
	Event string `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// Payload of the event.
	Payload *anypb.Any `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Type of action associated with event.
	Action        *v1beta1.ActionType `protobuf:"varint,4,opt,name=action,proto3,enum=dtkt.shared.v1beta1.ActionType,oneof" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPushEventsResponse) Reset() {
	*x = StreamPushEventsResponse{}
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPushEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPushEventsResponse) ProtoMessage() {}

func (x *StreamPushEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamPushEventsResponse) GetEventSource() string {
	if x != nil {
		return x.EventSource
	}
	return ""
}

func (x *StreamPushEventsResponse) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *StreamPushEventsResponse) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamPushEventsResponse) GetAction() v1beta1.ActionType {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return v1beta1.ActionType(0)
}

func (x *StreamPushEventsResponse) SetEventSource(v string) {
	x.EventSource = v
}

func (x *StreamPushEventsResponse) SetEvent(v string) {
	x.Event = v
}

func (x *StreamPushEventsResponse) SetPayload(v *anypb.Any) {
	x.Payload = v
}

func (x *StreamPushEventsResponse) SetAction(v v1beta1.ActionType) {
	x.Action = &v
}

func (x *StreamPushEventsResponse) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.Payload != nil
}

func (x *StreamPushEventsResponse) HasAction() bool {
	if x == nil {
		return false
	}
	return x.Action != nil
}

func (x *StreamPushEventsResponse) ClearPayload() {
	x.Payload = nil
}

func (x *StreamPushEventsResponse) ClearAction() {
	x.Action = nil
}

type StreamPushEventsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of push event source from request.
	EventSource string
	// Name of event delivered by event source.
	Event string
	// Payload of the event.
	Payload *anypb.Any
	// Type of action associated with event.
	Action *v1beta1.ActionType
}

func (b0 StreamPushEventsResponse_builder) Build() *StreamPushEventsResponse {
	m0 := &StreamPushEventsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.EventSource = b.EventSource
	x.Event = b.Event
	x.Payload = b.Payload
	x.Action = b.Action
	return m0
}

// Request to create a new event source.
type CreateEventSourceRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// ID of event source to create (e.g. `new-email-received-source`). This will
	// be combined with the prefix `event_sources/` to form the full name of the
	// event source (e.g. `event_sources/new-email-received-source`).
	EventSourceId string `protobuf:"bytes,1,opt,name=event_source_id,json=eventSourceId,proto3" json:"event_source_id,omitempty"`
	// Configuration of the event source.
	EventSource   *EventSource `protobuf:"bytes,2,opt,name=event_source,json=eventSource,proto3" json:"event_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventSourceRequest) Reset() {
	*x = CreateEventSourceRequest{}
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventSourceRequest) ProtoMessage() {}

func (x *CreateEventSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateEventSourceRequest) GetEventSourceId() string {
	if x != nil {
		return x.EventSourceId
	}
	return ""
}

func (x *CreateEventSourceRequest) GetEventSource() *EventSource {
	if x != nil {
		return x.EventSource
	}
	return nil
}

func (x *CreateEventSourceRequest) SetEventSourceId(v string) {
	x.EventSourceId = v
}

func (x *CreateEventSourceRequest) SetEventSource(v *EventSource) {
	x.EventSource = v
}

func (x *CreateEventSourceRequest) HasEventSource() bool {
	if x == nil {
		return false
	}
	return x.EventSource != nil
}

func (x *CreateEventSourceRequest) ClearEventSource() {
	x.EventSource = nil
}

type CreateEventSourceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// ID of event source to create (e.g. `new-email-received-source`). This will
	// be combined with the prefix `event_sources/` to form the full name of the
	// event source (e.g. `event_sources/new-email-received-source`).
	EventSourceId string
	// Configuration of the event source.
	EventSource *EventSource
}

func (b0 CreateEventSourceRequest_builder) Build() *CreateEventSourceRequest {
	m0 := &CreateEventSourceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.EventSourceId = b.EventSourceId
	x.EventSource = b.EventSource
	return m0
}

// Response for creating an event source.
type CreateEventSourceResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The created event source.
	EventSource   *EventSource `protobuf:"bytes,1,opt,name=event_source,json=eventSource,proto3" json:"event_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventSourceResponse) Reset() {
	*x = CreateEventSourceResponse{}
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventSourceResponse) ProtoMessage() {}

func (x *CreateEventSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateEventSourceResponse) GetEventSource() *EventSource {
	if x != nil {
		return x.EventSource
	}
	return nil
}

func (x *CreateEventSourceResponse) SetEventSource(v *EventSource) {
	x.EventSource = v
}

func (x *CreateEventSourceResponse) HasEventSource() bool {
	if x == nil {
		return false
	}
	return x.EventSource != nil
}

func (x *CreateEventSourceResponse) ClearEventSource() {
	x.EventSource = nil
}

type CreateEventSourceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The created event source.
	EventSource *EventSource
}

func (b0 CreateEventSourceResponse_builder) Build() *CreateEventSourceResponse {
	m0 := &CreateEventSourceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.EventSource = b.EventSource
	return m0
}

// Request to update an event source.
type UpdateEventSourceRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The event source to update, identified by its full name (e.g. `event_sources/new-email-received-source`).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Event source to update.
	EventSource   *EventSource `protobuf:"bytes,2,opt,name=event_source,json=eventSource,proto3" json:"event_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventSourceRequest) Reset() {
	*x = UpdateEventSourceRequest{}
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventSourceRequest) ProtoMessage() {}

func (x *UpdateEventSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateEventSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEventSourceRequest) GetEventSource() *EventSource {
	if x != nil {
		return x.EventSource
	}
	return nil
}

func (x *UpdateEventSourceRequest) SetName(v string) {
	x.Name = v
}

func (x *UpdateEventSourceRequest) SetEventSource(v *EventSource) {
	x.EventSource = v
}

func (x *UpdateEventSourceRequest) HasEventSource() bool {
	if x == nil {
		return false
	}
	return x.EventSource != nil
}

func (x *UpdateEventSourceRequest) ClearEventSource() {
	x.EventSource = nil
}

type UpdateEventSourceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The event source to update, identified by its full name (e.g. `event_sources/new-email-received-source`).
	Name string
	// Event source to update.
	EventSource *EventSource
}

func (b0 UpdateEventSourceRequest_builder) Build() *UpdateEventSourceRequest {
	m0 := &UpdateEventSourceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Name = b.Name
	x.EventSource = b.EventSource
	return m0
}

// Response for updating an event source.
type UpdateEventSourceResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The updated event source.
	EventSource   *EventSource `protobuf:"bytes,3,opt,name=event_source,json=eventSource,proto3" json:"event_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventSourceResponse) Reset() {
	*x = UpdateEventSourceResponse{}
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventSourceResponse) ProtoMessage() {}

func (x *UpdateEventSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateEventSourceResponse) GetEventSource() *EventSource {
	if x != nil {
		return x.EventSource
	}
	return nil
}

func (x *UpdateEventSourceResponse) SetEventSource(v *EventSource) {
	x.EventSource = v
}

func (x *UpdateEventSourceResponse) HasEventSource() bool {
	if x == nil {
		return false
	}
	return x.EventSource != nil
}

func (x *UpdateEventSourceResponse) ClearEventSource() {
	x.EventSource = nil
}

type UpdateEventSourceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The updated event source.
	EventSource *EventSource
}

func (b0 UpdateEventSourceResponse_builder) Build() *UpdateEventSourceResponse {
	m0 := &UpdateEventSourceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.EventSource = b.EventSource
	return m0
}

// Request to delete an event source.
type DeleteEventSourceRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The event source to delete, identified by its full name (e.g. `event_sources/new-email-received-source`).
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventSourceRequest) Reset() {
	*x = DeleteEventSourceRequest{}
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventSourceRequest) ProtoMessage() {}

func (x *DeleteEventSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteEventSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteEventSourceRequest) SetName(v string) {
	x.Name = v
}

type DeleteEventSourceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The event source to delete, identified by its full name (e.g. `event_sources/new-email-received-source`).
	Name string
}

func (b0 DeleteEventSourceRequest_builder) Build() *DeleteEventSourceRequest {
	m0 := &DeleteEventSourceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Name = b.Name
	return m0
}

// Response for deleting an event source.
type DeleteEventSourceResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventSourceResponse) Reset() {
	*x = DeleteEventSourceResponse{}
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventSourceResponse) ProtoMessage() {}

func (x *DeleteEventSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtkt_event_v1beta1_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteEventSourceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteEventSourceResponse_builder) Build() *DeleteEventSourceResponse {
	m0 := &DeleteEventSourceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_dtkt_event_v1beta1_messages_proto protoreflect.FileDescriptor

const file_dtkt_event_v1beta1_messages_proto_rawDesc = "" +
	"\n" +
	"!dtkt/event/v1beta1/messages.proto\x12\x12dtkt.event.v1beta1\x1a\x1bbuf/validate/validate.proto\x1a&dtkt/protoform/v1beta1/protoform.proto\x1a\x1fdtkt/shared/v1beta1/enums.proto\x1a\"dtkt/shared/v1beta1/messages.proto\x1a\x19google/api/resource.proto\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\"\xdb\x01\n" +
	"\x05Event\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12F\n" +
	"\x0epayload_schema\x18\x04 \x01(\v2\x1f.dtkt.shared.v1beta1.TypeSchemaR\rpayloadSchema:)\xeaA&\n" +
	"\x05Event\x12\x0eevents/{event}*\x06events2\x05event\"\xea\x04\n" +
	"\vEventSource\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12D\n" +
	"\rconfig_schema\x18\x04 \x01(\v2\x1f.dtkt.shared.v1beta1.TypeSchemaR\fconfigSchema\x12'\n" +
	"\x0frequires_config\x18\x05 \x01(\bR\x0erequiresConfig\x12*\n" +
	"\x11continue_on_error\x18\x06 \x01(\bR\x0fcontinueOnError\x12,\n" +
	"\x06config\x18\a \x01(\v2\x14.google.protobuf.AnyR\x06config\x12;\n" +
	"\x05state\x18\b \x01(\x0e2%.dtkt.event.v1beta1.EventSource.StateR\x05state\x128\n" +
	"\tpull_freq\x18\t \x01(\v2\x19.google.protobuf.DurationH\x00R\bpullFreq\x12\x1b\n" +
	"\bpush_url\x18\n" +
	" \x01(\tH\x00R\apushUrl\"D\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSTATE_ACTIVE\x10\x01\x12\x12\n" +
	"\x0eSTATE_INACTIVE\x10\x02:K\xeaAH\n" +
	"\vEventSource\x12\x1cevent_sources/{event_source}*\revent_sources2\fevent_sourceB\n" +
	"\n" +
	"\bstrategy\"s\n" +
	"\x11ListEventsRequest\x12'\n" +
	"\tpage_size\x18\x01 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"o\n" +
	"\x12ListEventsResponse\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.dtkt.event.v1beta1.EventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"y\n" +
	"\x17ListEventSourcesRequest\x12'\n" +
	"\tpage_size\x18\x01 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"\x88\x01\n" +
	"\x18ListEventSourcesResponse\x12D\n" +
	"\revent_sources\x18\x01 \x03(\v2\x1f.dtkt.event.v1beta1.EventSourceR\feventSources\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xc1\x02\n" +
	"\x17StreamPullEventsRequest\x12\xbf\x01\n" +
	"\x04name\x18\x01 \x01(\tB\xaa\x01\xbaH\x03\xc8\x01\x01\x82\xb5\x18\x9f\x01\n" +
	"\x1aSelect a pull event source:\x80\x01\n" +
	"0dtkt.event.v1beta1.EventService.ListEventSources\x12)this.event_sources.map(i, i.display_name)\x1a!this.event_sources.map(i, i.name)R\x04name\x12,\n" +
	"\x06config\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x06config\x126\n" +
	"\tpull_freq\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bpullFreq\"\xcc\x01\n" +
	"\x18StreamPullEventsResponse\x12!\n" +
	"\fevent_source\x18\x01 \x01(\tR\veventSource\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12.\n" +
	"\apayload\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\apayload\x12<\n" +
	"\x06action\x18\x04 \x01(\x0e2\x1f.dtkt.shared.v1beta1.ActionTypeH\x00R\x06action\x88\x01\x01B\t\n" +
	"\a_action\"\xa0\x03\n" +
	"\x17StreamPushEventsRequest\x12\xbf\x01\n" +
	"\x04name\x18\x01 \x01(\tB\xaa\x01\xbaH\x03\xc8\x01\x01\x82\xb5\x18\x9f\x01\n" +
	"\x1aSelect a push event source:\x80\x01\n" +
	"0dtkt.event.v1beta1.EventService.ListEventSources\x12)this.event_sources.map(i, i.display_name)\x1a!this.event_sources.map(i, i.name)R\x04name\x12R\n" +
	"\aheaders\x18\x02 \x03(\v28.dtkt.event.v1beta1.StreamPushEventsRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a[\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.dtkt.shared.v1beta1.StringListR\x05value:\x028\x01\"\xcc\x01\n" +
	"\x18StreamPushEventsResponse\x12!\n" +
	"\fevent_source\x18\x01 \x01(\tR\veventSource\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12.\n" +
	"\apayload\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\apayload\x12<\n" +
	"\x06action\x18\x04 \x01(\x0e2\x1f.dtkt.shared.v1beta1.ActionTypeH\x00R\x06action\x88\x01\x01B\t\n" +
	"\a_action\"\x8e\x01\n" +
	"\x18CreateEventSourceRequest\x12.\n" +
	"\x0fevent_source_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\reventSourceId\x12B\n" +
	"\fevent_source\x18\x02 \x01(\v2\x1f.dtkt.event.v1beta1.EventSourceR\veventSource\"_\n" +
	"\x19CreateEventSourceResponse\x12B\n" +
	"\fevent_source\x18\x01 \x01(\v2\x1f.dtkt.event.v1beta1.EventSourceR\veventSource\"z\n" +
	"\x18UpdateEventSourceRequest\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12B\n" +
	"\fevent_source\x18\x02 \x01(\v2\x1f.dtkt.event.v1beta1.EventSourceR\veventSource\"_\n" +
	"\x19UpdateEventSourceResponse\x12B\n" +
	"\fevent_source\x18\x03 \x01(\v2\x1f.dtkt.event.v1beta1.EventSourceR\veventSource\"6\n" +
	"\x18DeleteEventSourceRequest\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\"\x1b\n" +
	"\x19DeleteEventSourceResponseB\xe1\x01\n" +
	"\x18proto.dtkt.event.v1beta1B\rMessagesProtoP\x01ZLgithub.com/datakit-dev/dtkt-sdk/sdk-go/proto/dtkt/event/v1beta1;eventv1beta1\xa2\x02\x03DEX\xaa\x02\x12Dtkt.Event.V1beta1\xca\x02\x12Dtkt\\Event\\V1beta1\xe2\x02\x1eDtkt\\Event\\V1beta1\\GPBMetadata\xea\x02\x14Dtkt::Event::V1beta1b\x06proto3"

var file_dtkt_event_v1beta1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dtkt_event_v1beta1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_dtkt_event_v1beta1_messages_proto_goTypes = []any{
	(EventSource_State)(0),            // 0: dtkt.event.v1beta1.EventSource.State
	(*Event)(nil),                     // 1: dtkt.event.v1beta1.Event
	(*EventSource)(nil),               // 2: dtkt.event.v1beta1.EventSource
	(*ListEventsRequest)(nil),         // 3: dtkt.event.v1beta1.ListEventsRequest
	(*ListEventsResponse)(nil),        // 4: dtkt.event.v1beta1.ListEventsResponse
	(*ListEventSourcesRequest)(nil),   // 5: dtkt.event.v1beta1.ListEventSourcesRequest
	(*ListEventSourcesResponse)(nil),  // 6: dtkt.event.v1beta1.ListEventSourcesResponse
	(*StreamPullEventsRequest)(nil),   // 7: dtkt.event.v1beta1.StreamPullEventsRequest
	(*StreamPullEventsResponse)(nil),  // 8: dtkt.event.v1beta1.StreamPullEventsResponse
	(*StreamPushEventsRequest)(nil),   // 9: dtkt.event.v1beta1.StreamPushEventsRequest
	(*StreamPushEventsResponse)(nil),  // 10: dtkt.event.v1beta1.StreamPushEventsResponse
	(*CreateEventSourceRequest)(nil),  // 11: dtkt.event.v1beta1.CreateEventSourceRequest
	(*CreateEventSourceResponse)(nil), // 12: dtkt.event.v1beta1.CreateEventSourceResponse
	(*UpdateEventSourceRequest)(nil),  // 13: dtkt.event.v1beta1.UpdateEventSourceRequest
	(*UpdateEventSourceResponse)(nil), // 14: dtkt.event.v1beta1.UpdateEventSourceResponse
	(*DeleteEventSourceRequest)(nil),  // 15: dtkt.event.v1beta1.DeleteEventSourceRequest
	(*DeleteEventSourceResponse)(nil), // 16: dtkt.event.v1beta1.DeleteEventSourceResponse
	nil,                               // 17: dtkt.event.v1beta1.StreamPushEventsRequest.HeadersEntry
	(*v1beta1.TypeSchema)(nil),        // 18: dtkt.shared.v1beta1.TypeSchema
	(*anypb.Any)(nil),                 // 19: google.protobuf.Any
	(*durationpb.Duration)(nil),       // 20: google.protobuf.Duration
	(v1beta1.ActionType)(0),           // 21: dtkt.shared.v1beta1.ActionType
	(*v1beta1.StringList)(nil),        // 22: dtkt.shared.v1beta1.StringList
}
var file_dtkt_event_v1beta1_messages_proto_depIdxs = []int32{
	18, // 0: dtkt.event.v1beta1.Event.payload_schema:type_name -> dtkt.shared.v1beta1.TypeSchema
	18, // 1: dtkt.event.v1beta1.EventSource.config_schema:type_name -> dtkt.shared.v1beta1.TypeSchema
	19, // 2: dtkt.event.v1beta1.EventSource.config:type_name -> google.protobuf.Any
	0,  // 3: dtkt.event.v1beta1.EventSource.state:type_name -> dtkt.event.v1beta1.EventSource.State
	20, // 4: dtkt.event.v1beta1.EventSource.pull_freq:type_name -> google.protobuf.Duration
	1,  // 5: dtkt.event.v1beta1.ListEventsResponse.events:type_name -> dtkt.event.v1beta1.Event
	2,  // 6: dtkt.event.v1beta1.ListEventSourcesResponse.event_sources:type_name -> dtkt.event.v1beta1.EventSource
	19, // 7: dtkt.event.v1beta1.StreamPullEventsRequest.config:type_name -> google.protobuf.Any
	20, // 8: dtkt.event.v1beta1.StreamPullEventsRequest.pull_freq:type_name -> google.protobuf.Duration
	19, // 9: dtkt.event.v1beta1.StreamPullEventsResponse.payload:type_name -> google.protobuf.Any
	21, // 10: dtkt.event.v1beta1.StreamPullEventsResponse.action:type_name -> dtkt.shared.v1beta1.ActionType
	17, // 11: dtkt.event.v1beta1.StreamPushEventsRequest.headers:type_name -> dtkt.event.v1beta1.StreamPushEventsRequest.HeadersEntry
	19, // 12: dtkt.event.v1beta1.StreamPushEventsResponse.payload:type_name -> google.protobuf.Any
	21, // 13: dtkt.event.v1beta1.StreamPushEventsResponse.action:type_name -> dtkt.shared.v1beta1.ActionType
	2,  // 14: dtkt.event.v1beta1.CreateEventSourceRequest.event_source:type_name -> dtkt.event.v1beta1.EventSource
	2,  // 15: dtkt.event.v1beta1.CreateEventSourceResponse.event_source:type_name -> dtkt.event.v1beta1.EventSource
	2,  // 16: dtkt.event.v1beta1.UpdateEventSourceRequest.event_source:type_name -> dtkt.event.v1beta1.EventSource
	2,  // 17: dtkt.event.v1beta1.UpdateEventSourceResponse.event_source:type_name -> dtkt.event.v1beta1.EventSource
	22, // 18: dtkt.event.v1beta1.StreamPushEventsRequest.HeadersEntry.value:type_name -> dtkt.shared.v1beta1.StringList
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_dtkt_event_v1beta1_messages_proto_init() }
func file_dtkt_event_v1beta1_messages_proto_init() {
	if File_dtkt_event_v1beta1_messages_proto != nil {
		return
	}
	file_dtkt_event_v1beta1_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*EventSource_PullFreq)(nil),
		(*EventSource_PushUrl)(nil),
	}
	file_dtkt_event_v1beta1_messages_proto_msgTypes[7].OneofWrappers = []any{}
	file_dtkt_event_v1beta1_messages_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dtkt_event_v1beta1_messages_proto_rawDesc), len(file_dtkt_event_v1beta1_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dtkt_event_v1beta1_messages_proto_goTypes,
		DependencyIndexes: file_dtkt_event_v1beta1_messages_proto_depIdxs,
		EnumInfos:         file_dtkt_event_v1beta1_messages_proto_enumTypes,
		MessageInfos:      file_dtkt_event_v1beta1_messages_proto_msgTypes,
	}.Build()
	File_dtkt_event_v1beta1_messages_proto = out.File
	file_dtkt_event_v1beta1_messages_proto_goTypes = nil
	file_dtkt_event_v1beta1_messages_proto_depIdxs = nil
}
