// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: dtkt/geo/v1beta1/services.proto

package geov1beta1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1beta1 "github.com/datakit-dev/dtkt-sdk/sdk-go/proto/dtkt/geo/v1beta1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GeoServiceName is the fully-qualified name of the GeoService service.
	GeoServiceName = "dtkt.geo.v1beta1.GeoService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GeoServiceListGeoSourcesProcedure is the fully-qualified name of the GeoService's ListGeoSources
	// RPC.
	GeoServiceListGeoSourcesProcedure = "/dtkt.geo.v1beta1.GeoService/ListGeoSources"
	// GeoServiceStreamGeoJsonProcedure is the fully-qualified name of the GeoService's StreamGeoJson
	// RPC.
	GeoServiceStreamGeoJsonProcedure = "/dtkt.geo.v1beta1.GeoService/StreamGeoJson"
)

// GeoServiceClient is a client for the dtkt.geo.v1beta1.GeoService service.
type GeoServiceClient interface {
	// Lists GeoSource results for given request.
	ListGeoSources(context.Context, *connect.Request[v1beta1.ListGeoSourcesRequest]) (*connect.ServerStreamForClient[v1beta1.ListGeoSourcesResponse], error)
	// Streams GeoJson results for given request.
	StreamGeoJson(context.Context, *connect.Request[v1beta1.StreamGeoJsonRequest]) (*connect.ServerStreamForClient[v1beta1.StreamGeoJsonResponse], error)
}

// NewGeoServiceClient constructs a client for the dtkt.geo.v1beta1.GeoService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGeoServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GeoServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	geoServiceMethods := v1beta1.File_dtkt_geo_v1beta1_services_proto.Services().ByName("GeoService").Methods()
	return &geoServiceClient{
		listGeoSources: connect.NewClient[v1beta1.ListGeoSourcesRequest, v1beta1.ListGeoSourcesResponse](
			httpClient,
			baseURL+GeoServiceListGeoSourcesProcedure,
			connect.WithSchema(geoServiceMethods.ByName("ListGeoSources")),
			connect.WithClientOptions(opts...),
		),
		streamGeoJson: connect.NewClient[v1beta1.StreamGeoJsonRequest, v1beta1.StreamGeoJsonResponse](
			httpClient,
			baseURL+GeoServiceStreamGeoJsonProcedure,
			connect.WithSchema(geoServiceMethods.ByName("StreamGeoJson")),
			connect.WithClientOptions(opts...),
		),
	}
}

// geoServiceClient implements GeoServiceClient.
type geoServiceClient struct {
	listGeoSources *connect.Client[v1beta1.ListGeoSourcesRequest, v1beta1.ListGeoSourcesResponse]
	streamGeoJson  *connect.Client[v1beta1.StreamGeoJsonRequest, v1beta1.StreamGeoJsonResponse]
}

// ListGeoSources calls dtkt.geo.v1beta1.GeoService.ListGeoSources.
func (c *geoServiceClient) ListGeoSources(ctx context.Context, req *connect.Request[v1beta1.ListGeoSourcesRequest]) (*connect.ServerStreamForClient[v1beta1.ListGeoSourcesResponse], error) {
	return c.listGeoSources.CallServerStream(ctx, req)
}

// StreamGeoJson calls dtkt.geo.v1beta1.GeoService.StreamGeoJson.
func (c *geoServiceClient) StreamGeoJson(ctx context.Context, req *connect.Request[v1beta1.StreamGeoJsonRequest]) (*connect.ServerStreamForClient[v1beta1.StreamGeoJsonResponse], error) {
	return c.streamGeoJson.CallServerStream(ctx, req)
}

// GeoServiceHandler is an implementation of the dtkt.geo.v1beta1.GeoService service.
type GeoServiceHandler interface {
	// Lists GeoSource results for given request.
	ListGeoSources(context.Context, *connect.Request[v1beta1.ListGeoSourcesRequest], *connect.ServerStream[v1beta1.ListGeoSourcesResponse]) error
	// Streams GeoJson results for given request.
	StreamGeoJson(context.Context, *connect.Request[v1beta1.StreamGeoJsonRequest], *connect.ServerStream[v1beta1.StreamGeoJsonResponse]) error
}

// NewGeoServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGeoServiceHandler(svc GeoServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	geoServiceMethods := v1beta1.File_dtkt_geo_v1beta1_services_proto.Services().ByName("GeoService").Methods()
	geoServiceListGeoSourcesHandler := connect.NewServerStreamHandler(
		GeoServiceListGeoSourcesProcedure,
		svc.ListGeoSources,
		connect.WithSchema(geoServiceMethods.ByName("ListGeoSources")),
		connect.WithHandlerOptions(opts...),
	)
	geoServiceStreamGeoJsonHandler := connect.NewServerStreamHandler(
		GeoServiceStreamGeoJsonProcedure,
		svc.StreamGeoJson,
		connect.WithSchema(geoServiceMethods.ByName("StreamGeoJson")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dtkt.geo.v1beta1.GeoService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GeoServiceListGeoSourcesProcedure:
			geoServiceListGeoSourcesHandler.ServeHTTP(w, r)
		case GeoServiceStreamGeoJsonProcedure:
			geoServiceStreamGeoJsonHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGeoServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGeoServiceHandler struct{}

func (UnimplementedGeoServiceHandler) ListGeoSources(context.Context, *connect.Request[v1beta1.ListGeoSourcesRequest], *connect.ServerStream[v1beta1.ListGeoSourcesResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.geo.v1beta1.GeoService.ListGeoSources is not implemented"))
}

func (UnimplementedGeoServiceHandler) StreamGeoJson(context.Context, *connect.Request[v1beta1.StreamGeoJsonRequest], *connect.ServerStream[v1beta1.StreamGeoJsonResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("dtkt.geo.v1beta1.GeoService.StreamGeoJson is not implemented"))
}
