version: "3"

env:
  GOEXPERIMENT: jsonv2

includes:
  go:
    taskfile: ${TASK_PATH}/Taskfile.go.yaml
    vars:
      GO_BUILD_BINARY: pkg

  sops:
    taskfile: ${TASK_PATH}/Taskfile.sops.yaml

  k:prd:
    taskfile: ${TASK_PATH}/Taskfile.kustomize.yaml
    dir: infra/kustomize/overlays/prd

  k:dev:
    taskfile: ${TASK_PATH}/Taskfile.kustomize.yaml
    dir: infra/kustomize/overlays/dev

tasks:
  setup:
    desc: Setup the dev environment
    cmds:
      - task: go:setup
      - buf dep update

  dev:
    cmds:
      - dtkt intgr dev

  generate:
    desc: Code generation
    cmds:
      - buf generate
      - task: go:generate

  vhs-tapes:
    desc: Generate vhs tapes
    cmds:
      - for: { var: TAPES, as: TAPE }
        cmd: vhs {{.TAPE}} -o $(dirname {{.TAPE}})/$(basename {{.TAPE}} .tape).gif
    vars:
      TAPES:
        sh: find ./examples -name '*.tape' {{.CLI_ARGS}}

  docs:
    desc: Generate documentation
    cmds:
      - task: vhs-tapes

  lint:
    cmds:
      - task: go:lint
      - buf lint

  build:
    cmds:
      - task: go:build

  test:
    cmds:
      - task: go:test
