name: Publish TypeScript SDK

on:
  release:
    types: [published]

jobs:
  build-publish:
    name: Build & Publish
    environment: prd
    if: startsWith(github.event.release.tag_name, 'sdk-ts-v')
    runs-on: ${{ vars.RUNNER }}

    # Needed for npm trusted publishers
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: datakit-dev/.github/actions/setup-monorepo@main
      with:
        dtkt-dev-sparse-checkout: |
          scripts
          tasks
        dtkt-core-sparse-checkout: packages
        dtkt-github-actions-app-id: ${{ vars.DTKT_GITHUB_ACTIONS_APP_ID }}
        dtkt-github-actions-private-key: ${{ secrets.DTKT_GITHUB_ACTIONS_PRIVATE_KEY }}

    - uses: datakit-dev/.github/actions/setup@main
      with:
        task: true
        node: true
        versions: ${{ vars.VERSIONS }}
        pnpm-cache-dependency-path: ./dtkt-universe/pnpm-lock.yaml

    - name: Build
      run: task build
      working-directory: ./dtkt-universe/dtkt-sdk/sdk-ts

    - name: Publish
      run: task publish
      working-directory: ./dtkt-universe/dtkt-sdk/sdk-ts
