name: Lint & Test Go SDK

on:
  pull_request:
    branches:
    - main
    paths:
    - sdk-go/**
    - .github/workflows/sdk-go.yaml

jobs:
  test:
    name: Lint & Test
    runs-on: ${{ vars.RUNNER }}

    steps:
    - uses: datakit-dev/.github/actions/setup-monorepo@main
      with:
        dtkt-dev-sparse-checkout: |
          scripts
          tasks
        dtkt-github-actions-app-id: ${{ vars.DTKT_GITHUB_ACTIONS_APP_ID }}
        dtkt-github-actions-private-key: ${{ secrets.DTKT_GITHUB_ACTIONS_PRIVATE_KEY }}

    - uses: datakit-dev/.github/actions/setup@main
      with:
        task: true
        go: true
        versions: ${{ vars.VERSIONS }}

    - name: Setup
      run: task setup
      working-directory: ./dtkt-universe/dtkt-sdk/sdk-go

    - name: Lint
      uses: golangci/golangci-lint-action@v9
      env:
        GOEXPERIMENT: jsonv2
      with:
        version: ${{ fromJSON(vars.VERSIONS).golangci-lint }}
        working-directory: ./dtkt-universe/dtkt-sdk/sdk-go
        args: --timeout=5m

    - name: Test
      run: task test
      working-directory: ./dtkt-universe/dtkt-sdk/sdk-go
